//>>built
require({cache:{"shell/multiTabCompanySwitchWarning/multiTabCompanySwitchWarning":function(){define(["exports","shell/util/featuresUtil","shell/shell-intl/nlsPrefetch!MultiTabCompanySwitchWarning","xstyle/css!shell/harmony/feature/MultiTabCompanySwitchWarning.css"],function(d,a,b,h){function m(b){if("undefined"===typeof document)return null;const a=document.createElement("div");a.innerHTML=b?b.trim():"";if(1===a.childNodes.length)return a.removeChild(a.firstChild);throw Error("Invalid template property was used. It cannot be empty or the node created resulted in multiple parent nodes",
b);}function c(){if(!e&&!a.default.isFeatureEnabled("qbo-shell-disable-multitab-warning")){if(!f){var c='\x3cdiv class\x3d"multi-tab-company-switch-warning"\x3e\n    \x3cdiv\x3e\n        \x3cdiv class\x3d"page-title-30light"\x3e{multi_company_switch_heading}\x3c/div\x3e\n        \x3cdiv class\x3d"subsection14TitleTextLight"\x3e\n            \x3cp\x3e{multi_company_switch_begin_stmt}\n            \x3cp\x3e{multi_company_switch_desc}\n            \x3cul\x3e\n                \x3cli\x3e{multi_company_switch_action_1}\n                \x3cli\x3e{multi_company_switch_action_2}\n            \x3c/ul\x3e\n            \x3cp\x3e\n            \x3cdiv class\x3d"caption"\x3e\n                \x3cstrong\x3e{multi_company_switch_tip}\x3c/strong\x3e {multi_company_switch_tip_desc}\n            \x3c/div\x3e\n        \x3c/div\x3e\n    \x3c/div\x3e\n\x3c/div\x3e'.replace(/\{([^}]+)\}/g,
(a,t)=>b.default[t]);f=m(c)}document.body.appendChild(f);e=!0}}var g=require("@babel/runtime/helpers/interopRequireDefault").default;Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;a=g(a);b=g(b);h=g(h);let e=!1;const k=qbo.serverGroupCompanyId,r=window.localStorage.getItem("currentCompanyIdForMultiTab");let f;d.default={start:()=>{k!==r&&window.localStorage.setItem("currentCompanyIdForMultiTab",k);window.addEventListener("storage",b=>{"currentCompanyIdForMultiTab"===b.key&&b.newValue&&
(b.newValue!==k?c():f&&e&&(document.body.removeChild(f),e=!1))})}};return d["default"]})},"shell/base/startupModules/paymentsModule":function(){define(["shell/util/CustomTopicImpl","neo/services/IPDService","shell/base/shellSandbox"],function(d,a,b){return{start:function(){return new Promise(function(h,m){d.subscribe("ipd/payments/refresh",function(c){(new a).isPaymentAvailable(!0).then(function(a){qbo.ipd.payments="true"===""+a;a=qbo.sku&&"ECOSYSTEM"!==qbo.sku.mnemonic;var e=qbo.ipd.payments||qbo.ipd.masReconDisabled,
g=c&&c.hideCOAMapper,m=c?c.bankName:"",f=c?c.accountNumber:"",p=c?c.type:"";d.publish("ipd/payments");!a||e||g||require(["shell/dialogs/DepositAccountDialogViewController"],function(a){a=new a;if(c&&c.isEditBank)a.onBankEdit();b.getSandbox().logger.info("paymentsModule: showing DepositAccountDialogViewController");a.setBankInfo({bankName:m,accountNumber:f});a.show(p);h({showDepositAccountDialogBox:!0})});h({showDepositAccountDialogBox:!1})},function(a){m(a)})})})}}})},"neo/services/IPDService":function(){function d(a){"@babel/helpers - typeof";
d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return d(a)}define("exports neo/BaseService neo/neoContext neo/util/urlUtil shell/base/shellSandbox ../util/_featuresUtil".split(" "),function(a,b,h,m,c,g){function e(a){return a&&a.__esModule?a:{"default":a}}function k(a,b){for(var n=0;n<b.length;n++){var l=b[n];l.enumerable=l.enumerable||!1;
l.configurable=!0;"value"in l&&(l.writable=!0);Object.defineProperty(a,l.key,l)}}function r(a,b,n){b&&k(a.prototype,b);n&&k(a,n);return a}function f(a){f=Object.setPrototypeOf?Object.getPrototypeOf:function(a){return a.__proto__||Object.getPrototypeOf(a)};return f(a)}function p(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&q(a,b)}function q(a,
b){q=Object.setPrototypeOf||function(a,b){a.__proto__=b;return a};return q(a,b)}Object.defineProperty(a,"__esModule",{value:!0});a["default"]=void 0;b=e(b);h=e(h);m=e(m);c=e(c);g=e(g);b=function(a){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var a=f(b).apply(this,arguments);if(!a||"object"!==d(a)&&"function"!==typeof a){if(void 0===this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=this}return a}p(b,a);r(b,
[{key:"getServiceUrl",value:function(a){return this.getUIServiceUrl("ipd/".concat(a))}},{key:"hideBuyNow",value:function(){return this.doXHRGet(this.getNeoServiceUrl("v1","ipd/hidebuynow"))}},{key:"getClassicLASMessages",value:function(){return this.doXHRGet(this.getNeoServiceUrl("v1","domoqb"))}},{key:"hasCustomers",value:function(){return this.doXHRGet(this.getNeoServiceUrl("v1","lists/name/store"),{content:{types:"customer",includeDeleted:!0}})}},{key:"canShowPayrollIpd",value:function(a){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1",
"ipd/showpayrollipd")).concat(a?"?refresh\x3dtrue":""))}},{key:"canShowClientMessage",value:function(a){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/showclientmessage")).concat(a?"?refresh\x3dtrue":""))}},{key:"isPaymentAvailable",value:function(a){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/showpaymentipd")).concat(a?"?refresh\x3dtrue":""))}},{key:"getMerchantAccountInfo",value:function(a){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/getMerchantAccountInfo")).concat(a?
"?refresh\x3dtrue":""))}},{key:"getActivityFeedRecommendations",value:function(a){return a?this.doXHRGet(this.getNeoServiceUrl("v1","activityfeed/feed")):this.doXHRGet(this.getNeoServiceUrl("v1","activityfeed/localfeed"))}},{key:"getJsonData",value:function(a){return a?this.doXHRGet(this.getNeoServiceUrl("v1","ipd/jsonDataActivityFeed")):this.doXHRGet(this.getNeoServiceUrl("v1","ipd/jsonDataLeftNav"))}},{key:"getLeftNavRecommendations",value:function(a,b){return b?this.doXHRGet("".concat(this.getServiceUrl("recommendationleftnav")).concat(a?
"?refresh\x3dtrue":"")):this.doXHRGet("".concat(this.getServiceUrl("recommendationleftnavlocal")).concat(a?"?refresh\x3dtrue":""))}},{key:"getActivityFeedRecommendation",value:function(a,b){b={source:b};a&&a.length&&(b.activities=a.join(","));return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/accesspoints"),"/activityfeed/recommendation"),{content:b})}},{key:"getAccessPointRecommendation",value:function(a,b,c,d){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/accesspoints"),
"/").concat(a,"/recommendation"),{content:{n:c,pid:b,source:d}})}},{key:"getPluginAccessPointRecommendations",value:function(a,b){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/accesspoints"),"/").concat(a,"/plugin/recommendations"),{content:{payload:b}})}},{key:"getAccessPointRecommendations",value:function(a,b){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/accesspoints"),"/").concat(a,"/recommendations"),{content:{source:b}})}},{key:"getAccessPointRecommendationById",
value:function(a,b,c){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/accesspoints"),"/").concat(a,"/recommendations/").concat(b),{content:{source:c}})}},{key:"getForcedRecommendationStorageConfig",value:function(){return{storageKeySuffix:"debug-ipd-forcedrec",storageType:"localStorage"}}},{key:"getIPPAppEntitlements",value:function(a){var b=this;return new Promise(function(n,d){require(["qbo-ui-libs-plugins/services/PluginRegistryService"],function(e){var f,l,h;e=e.findById("sbg-web-shell-ui");
var g=null!==(f=window)&&void 0!==f&&null!==(l=f.__shellInternal)&&void 0!==l&&null!==(h=l.qboContext)&&void 0!==h&&h.isCoreAppEnabled?m["default"].getGatewayV1ServiceUrl("plugins/info/qbo-web-app-experience?refreshIppAlways\x3d".concat(!!a,"\x26refreshIppSync\x3dtrue")):"".concat(b.getNeoServiceUrl("v1","ipd/IPPAppEntitlements"),"?refresh\x3d").concat(!!a);e&&(f=e.version,g="".concat(g,"\x26shellVersion\x3d").concat(f));var k=c["default"].getSandbox(),p=Date.now();b.doXHRGet(g).then(function(a){null===
k||void 0===k?void 0:k.logger.info("services/IPDService: getIPPAppEntitlements",{apiUrl:g,timeTaken:Date.now()-p,outcome:"success"});n(a)})["catch"](function(a){null===k||void 0===k?void 0:k.logger.error("services/IPDService: getIPPAppEntitlements",{err:(null===a||void 0===a?void 0:a.message)||"failed to get plugin data",apiUrl:g,timeTaken:Date.now()-p,outcome:"fail"});d(a)})})})}},{key:"doPluginActivation",value:function(a,b){return this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/doPluginActivation"),
"?pluginId\x3d").concat(a,"\x26activated\x3d").concat(b))}},{key:"setPreferencesOnFingerprints",value:function(a){this.doXHRGet("".concat(this.getNeoServiceUrl("v1","ipd/fingerprintsPreference"),"?id\x3d").concat(a))}},{key:"getSignedAuthData",value:function(){return this.doXHRGet(this.getNeoServiceUrl("v1","ipd/signedAuthData"))}},{key:"showXthPaymentIPD",value:function(){return this.doXHRGet(this.getNeoServiceUrl("v1","ipd/showXthPaymentIPD"))}},{key:"setXthPaymentIPDStateBit",value:function(a){return this.doXHRPost("".concat(this.getNeoServiceUrl("v1",
"ipd/setXthPaymentIPDStateBit"),"/").concat(a),{})}},{key:"getIPDConfigInfo",value:function(){var a="/company/".concat(h["default"].getContextParam("serverGroupCompanyId"),"/uibootstrap/ipd"),b=g["default"].isFeatureEnabled("qbo-shell-use-gateway-endpoint");a="".concat(m["default"].getBaseUrl()).concat(b?"/api":"","/v1/").concat(a);return this.doXHRGet(a)}}]);return b}(b["default"]);a["default"]=b;return a["default"]})},"shell/shell/deferred-css-load/deferredLoad":function(){define([],function(){var d=
qbo.showFTU?5E3:0;return{start:function(){setTimeout(function(){this.insertCSSFiles()}.bind(this),d)},insertCSSFiles:function(){var a=[];a.push("shell/harmony/harmony-legacy.css");a.push("shell/harmony/svg.css");0<a.length&&(a=a.map(function(a){return"xstyle/css!"+a}),require(a,function(){},function(a){console.error("ERROR while loading deferred CSS Layers!:");console.error(a)}))}}})}}});define("shell/afterPageReadyDeps",[],1);
//# sourceMappingURL=afterPageReadyDeps.js.map