// ============================================
//  CLOUD THEORY — MOCK DATA
//  Swap fetch() calls here to connect live API
// ============================================

const DealerDataByAccount = {

  "South Bay Ford": {
    dealer: { name: "South Bay Ford", location: "Hawthorne, CA", rooftop: "Rooftop 04" },
    stats: [
      { label: "Total Sales MTD", value: "247", delta: "+12%", trend: "up", sub: "vs last month" },
      { label: "Revenue MTD", value: "$6.4M", delta: "+8.3%", trend: "up", sub: "vs last month" },
      { label: "Units in Stock", value: "1,082", delta: "-4.1%", trend: "down", sub: "vs 30-day avg" },
      { label: "Incoming Shipments", value: "138", delta: "+22", trend: "up", sub: "next 14 days" },
    ],
    inventory: [
      { type: "New",  make: "Ford", model: "F-150",        stock: 104, daysOnLot: 18, price: "$42,500", status: "available" },
      { type: "New",  make: "Ford", model: "Explorer",     stock: 67,  daysOnLot: 24, price: "$48,200", status: "available" },
      { type: "New",  make: "Ford", model: "Mustang",      stock: 31,  daysOnLot: 9,  price: "$38,900", status: "available" },
      { type: "New",  make: "Ford", model: "Bronco",       stock: 22,  daysOnLot: 33, price: "$52,100", status: "low" },
      { type: "New",  make: "Ford", model: "Maverick",     stock: 58,  daysOnLot: 14, price: "$27,300", status: "available" },
      { type: "New",  make: "Ford", model: "Escape",       stock: 43,  daysOnLot: 41, price: "$31,600", status: "aging" },
      { type: "Used", make: "Ford", model: "F-150",        stock: 29,  daysOnLot: 22, price: "$34,800", status: "available" },
      { type: "Used", make: "Ford", model: "Edge",         stock: 17,  daysOnLot: 55, price: "$29,400", status: "aging" },
      { type: "New",  make: "Ford", model: "Ranger",       stock: 38,  daysOnLot: 12, price: "$36,700", status: "available" },
      { type: "New",  make: "Ford", model: "Expedition",   stock: 14,  daysOnLot: 47, price: "$62,400", status: "aging" },
      { type: "Used", make: "Ford", model: "Bronco Sport", stock: 21,  daysOnLot: 28, price: "$33,200", status: "available" },
      { type: "New",  make: "Ford", model: "Transit",      stock: 9,   daysOnLot: 62, price: "$44,900", status: "aging" },
      { type: "Used", make: "Ford", model: "Explorer",     stock: 24,  daysOnLot: 19, price: "$39,600", status: "available" },
      { type: "New",  make: "Ford", model: "Mustang Mach-E", stock: 16, daysOnLot: 7, price: "$45,800", status: "available" },
      { type: "Used", make: "Ford", model: "Maverick",     stock: 12,  daysOnLot: 35, price: "$24,100", status: "low" },
      { type: "New",  make: "Ford", model: "Super Duty",   stock: 27,  daysOnLot: 15, price: "$58,300", status: "available" },
      { type: "Used", make: "Ford", model: "Escape",       stock: 19,  daysOnLot: 44, price: "$26,500", status: "aging" },
      { type: "New",  make: "Ford", model: "Edge",         stock: 11,  daysOnLot: 51, price: "$41,200", status: "aging" },
      { type: "Used", make: "Ford", model: "Ranger",       stock: 8,   daysOnLot: 30, price: "$31,900", status: "low" },
    ],
    shipments: [
      { eta: "Mar 09", model: "F-150 XLT",      qty: 18, make: "Ford", status: "confirmed" },
      { eta: "Mar 11", model: "Explorer ST",     qty: 12, make: "Ford", status: "confirmed" },
      { eta: "Mar 14", model: "Mustang GT",      qty: 6,  make: "Ford", status: "confirmed" },
      { eta: "Mar 17", model: "Bronco Wildtrak", qty: 9,  make: "Ford", status: "in-transit" },
      { eta: "Mar 19", model: "Maverick Hybrid", qty: 24, make: "Ford", status: "in-transit" },
      { eta: "Mar 22", model: "F-150 Raptor",    qty: 4,  make: "Ford", status: "pending" },
      { eta: "Mar 25", model: "Escape Plug-In",  qty: 15, make: "Ford", status: "pending" },
    ],
    aiSummary: {
      generatedAt: "Today, 8:04 AM",
      headline: "Strong month-to-date performance with inventory pressure building.",
      insights: [
        "F-150 continues to lead sales volume — stock down 4.1% vs. 30-day average. Prioritize incoming Mar 9 shipment to prevent stockout risk.",
        "Escape inventory is aging at 41 days average. Consider incentive adjustment or targeted marketing to accelerate turns.",
        "Bronco supply is critically low (22 units). 9 units incoming Mar 17 — high demand model, expect rapid absorption.",
        "Revenue per unit is up 3.2% driven by stronger Mustang and F-150 Raptor mix. Lean into high-margin trim upsells.",
        "22 incoming Maverick Hybrids on Mar 19 — market demand is high and days-to-sale avg is 11 days. No action needed.",
      ],
      recommendations: [
        { tag: "Pricing", text: "Hawthorne Ford (competitor) has sold 32 more vehicles than you this month. Based on our analysis, your average listing price is 15% higher across overlapping models. We recommend evaluating pricing on Explorer, Escape, and Edge to close the gap." },
        { tag: "Inventory", text: "Your F-150 turn rate is 2.3x faster than the regional average, but you're carrying 40% less stock than nearby dealers. Increasing F-150 allocation by 15–20 units could capture an estimated $680K in additional monthly revenue." },
        { tag: "Marketing", text: "Bronco Sport search volume in your zip codes is up 28% week-over-week, but your digital ad spend on that model is flat. Reallocating $2K from Escape campaigns to Bronco Sport could improve cost-per-lead by an estimated 35%." },
        { tag: "Incentive", text: "3 competitors within 10 miles are running 0% APR on Escape through March. Your Escape inventory is aging at 41 days — matching or beating this offer could move 12–15 units before month-end." },
      ],
    },
    salesTrend: {
      labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
      units:  [198, 221, 189, 234, 261, 247],
    },
    mapCenter: [33.916, -118.352],
    salesPoints: [
      { lat: 33.916, lng: -118.352, label: "South Bay Ford", sales: 247, type: "dealer" },
      { lat: 33.942, lng: -118.396, label: "El Segundo", sales: 34 },
      { lat: 33.895, lng: -118.370, label: "Gardena", sales: 28 },
      { lat: 33.880, lng: -118.310, label: "Torrance", sales: 41 },
      { lat: 33.930, lng: -118.328, label: "Lawndale", sales: 19 },
      { lat: 33.862, lng: -118.399, label: "Redondo Beach", sales: 37 },
      { lat: 33.952, lng: -118.340, label: "Inglewood", sales: 22 },
      { lat: 33.835, lng: -118.345, label: "Lomita", sales: 15 },
      { lat: 33.870, lng: -118.260, label: "Carson", sales: 26 },
      { lat: 33.906, lng: -118.420, label: "Manhattan Beach", sales: 25 },
    ],
  },

  "South Bay Ford Lincoln": {
    dealer: { name: "South Bay Ford Lincoln", location: "Hawthorne, CA", rooftop: "Rooftop 02" },
    stats: [
      { label: "Total Sales MTD", value: "89", delta: "+6%", trend: "up", sub: "vs last month" },
      { label: "Revenue MTD", value: "$4.2M", delta: "+3.1%", trend: "up", sub: "vs last month" },
      { label: "Units in Stock", value: "412", delta: "+2.3%", trend: "up", sub: "vs 30-day avg" },
      { label: "Incoming Shipments", value: "34", delta: "+8", trend: "up", sub: "next 14 days" },
    ],
    inventory: [
      { type: "New",  make: "Lincoln", model: "Aviator",     stock: 28, daysOnLot: 31, price: "$58,900", status: "available" },
      { type: "New",  make: "Lincoln", model: "Nautilus",    stock: 22, daysOnLot: 19, price: "$46,200", status: "available" },
      { type: "New",  make: "Lincoln", model: "Navigator",   stock: 11, daysOnLot: 42, price: "$82,400", status: "aging" },
      { type: "New",  make: "Lincoln", model: "Corsair",     stock: 35, daysOnLot: 15, price: "$39,800", status: "available" },
      { type: "Used", make: "Lincoln", model: "Aviator",     stock: 14, daysOnLot: 27, price: "$48,500", status: "available" },
      { type: "Used", make: "Lincoln", model: "Navigator",   stock: 8,  daysOnLot: 58, price: "$64,200", status: "aging" },
      { type: "New",  make: "Ford",    model: "F-150",       stock: 42, daysOnLot: 20, price: "$44,100", status: "available" },
      { type: "New",  make: "Ford",    model: "Explorer",    stock: 31, daysOnLot: 25, price: "$49,300", status: "available" },
      { type: "Used", make: "Lincoln", model: "Corsair",     stock: 9,  daysOnLot: 36, price: "$33,700", status: "low" },
      { type: "New",  make: "Ford",    model: "Bronco",      stock: 18, daysOnLot: 11, price: "$51,800", status: "available" },
    ],
    shipments: [
      { eta: "Mar 10", model: "Aviator Reserve",   qty: 8,  make: "Lincoln", status: "confirmed" },
      { eta: "Mar 13", model: "Navigator Black Label", qty: 3, make: "Lincoln", status: "confirmed" },
      { eta: "Mar 16", model: "Corsair Grand Touring", qty: 10, make: "Lincoln", status: "in-transit" },
      { eta: "Mar 20", model: "Nautilus Reserve",  qty: 6,  make: "Lincoln", status: "pending" },
      { eta: "Mar 23", model: "F-150 Platinum",    qty: 7,  make: "Ford", status: "pending" },
    ],
    aiSummary: {
      generatedAt: "Today, 8:04 AM",
      headline: "Lincoln segment steady with Navigator aging risk.",
      insights: [
        "Aviator is your top performer — 28 units moving at healthy pace. New shipment of 8 Reserve trims arriving Mar 10 will meet demand.",
        "Navigator inventory is aging at 42 days. Consider $2K dealer incentive to move 3–4 units before month-end.",
        "Corsair Grand Touring demand is spiking — 10 units incoming Mar 16 should be pre-allocated to existing leads.",
        "Lincoln segment revenue per unit is 38% higher than Ford models. Continue prioritizing luxury trim upsells.",
      ],
      recommendations: [
        { tag: "Pricing", text: "Your Navigator pricing is 8% above regional average. Keyes Lincoln has moved 5 more Navigators this month at lower ASPs. Consider aligning pricing to capture lost demand." },
        { tag: "Marketing", text: "Lincoln Aviator search interest in your area is up 18% but your SEM budget hasn't changed. A $1.5K increase could capture 10+ additional qualified leads." },
        { tag: "Incentive", text: "Ford is offering $3K loyalty bonus on Corsair through March. Promote this aggressively to conquest BMW X1 and Audi Q3 shoppers in your CRM." },
      ],
    },
    salesTrend: {
      labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
      units:  [72, 81, 65, 78, 94, 89],
    },
    mapCenter: [33.916, -118.352],
    salesPoints: [
      { lat: 33.916, lng: -118.352, label: "South Bay Ford Lincoln", sales: 89, type: "dealer" },
      { lat: 33.942, lng: -118.396, label: "El Segundo", sales: 12 },
      { lat: 33.880, lng: -118.310, label: "Torrance", sales: 18 },
      { lat: 33.862, lng: -118.399, label: "Redondo Beach", sales: 14 },
      { lat: 33.952, lng: -118.340, label: "Inglewood", sales: 9 },
      { lat: 33.906, lng: -118.420, label: "Manhattan Beach", sales: 21 },
    ],
  },

  "South Bay Lincoln": {
    dealer: { name: "South Bay Lincoln", location: "Torrance, CA", rooftop: "Rooftop 01" },
    stats: [
      { label: "Total Sales MTD", value: "54", delta: "-3%", trend: "down", sub: "vs last month" },
      { label: "Revenue MTD", value: "$3.1M", delta: "-1.8%", trend: "down", sub: "vs last month" },
      { label: "Units in Stock", value: "218", delta: "+6.2%", trend: "up", sub: "vs 30-day avg" },
      { label: "Incoming Shipments", value: "19", delta: "+4", trend: "up", sub: "next 14 days" },
    ],
    inventory: [
      { type: "New",  make: "Lincoln", model: "Aviator",   stock: 19, daysOnLot: 34, price: "$57,400", status: "low" },
      { type: "New",  make: "Lincoln", model: "Nautilus",  stock: 26, daysOnLot: 22, price: "$45,800", status: "available" },
      { type: "New",  make: "Lincoln", model: "Navigator", stock: 7,  daysOnLot: 61, price: "$84,100", status: "aging" },
      { type: "New",  make: "Lincoln", model: "Corsair",   stock: 32, daysOnLot: 17, price: "$40,200", status: "available" },
      { type: "Used", make: "Lincoln", model: "Aviator",   stock: 11, daysOnLot: 44, price: "$46,900", status: "aging" },
      { type: "Used", make: "Lincoln", model: "Nautilus",  stock: 15, daysOnLot: 29, price: "$37,300", status: "available" },
      { type: "Used", make: "Lincoln", model: "Corsair",   stock: 8,  daysOnLot: 38, price: "$32,100", status: "low" },
      { type: "New",  make: "Lincoln", model: "Navigator L", stock: 4, daysOnLot: 55, price: "$92,600", status: "aging" },
    ],
    shipments: [
      { eta: "Mar 12", model: "Corsair Standard", qty: 7, make: "Lincoln", status: "confirmed" },
      { eta: "Mar 15", model: "Nautilus Reserve",  qty: 5, make: "Lincoln", status: "confirmed" },
      { eta: "Mar 21", model: "Aviator Grand Touring", qty: 4, make: "Lincoln", status: "in-transit" },
      { eta: "Mar 26", model: "Navigator Reserve", qty: 3, make: "Lincoln", status: "pending" },
    ],
    aiSummary: {
      generatedAt: "Today, 8:04 AM",
      headline: "Sales softening slightly — aging inventory needs attention.",
      insights: [
        "Sales are down 3% MTD vs. last month. Corsair remains the volume leader but Aviator demand is cooling.",
        "Navigator and Navigator L have a combined 11 units aging past 55 days. These need immediate pricing action.",
        "Used Aviator stock is aging at 44 days — 11 units sitting. Consider wholesale disposition for 4–5 oldest units.",
        "Nautilus is performing well at 22 days average. Incoming shipment of 5 Reserve trims on Mar 15 is well-timed.",
      ],
      recommendations: [
        { tag: "Pricing", text: "Your Navigator L is priced 6% above AutoNation Lincoln. They've sold 3 units this month vs. your 0. Drop price by $4K to compete." },
        { tag: "Inventory", text: "Used Aviator and Corsair are aging. Consider running a certified pre-owned event this weekend to move 6–8 units and free up floor space." },
        { tag: "Marketing", text: "Corsair search volume is flat but Nautilus interest is rising 12% WoW. Shift $1K of digital budget from Corsair to Nautilus campaigns." },
      ],
    },
    salesTrend: {
      labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
      units:  [61, 58, 49, 63, 56, 54],
    },
    mapCenter: [33.840, -118.340],
    salesPoints: [
      { lat: 33.840, lng: -118.340, label: "South Bay Lincoln", sales: 54, type: "dealer" },
      { lat: 33.880, lng: -118.310, label: "Torrance", sales: 16 },
      { lat: 33.862, lng: -118.399, label: "Redondo Beach", sales: 11 },
      { lat: 33.835, lng: -118.345, label: "Lomita", sales: 8 },
      { lat: 33.810, lng: -118.380, label: "Palos Verdes", sales: 14 },
    ],
  },

  "Galpin Ford": {
    dealer: { name: "Galpin Ford", location: "North Hills, CA", rooftop: "Rooftop 01" },
    stats: [
      { label: "Total Sales MTD", value: "382", delta: "+18%", trend: "up", sub: "vs last month" },
      { label: "Revenue MTD", value: "$11.2M", delta: "+14.5%", trend: "up", sub: "vs last month" },
      { label: "Units in Stock", value: "2,140", delta: "-2.8%", trend: "down", sub: "vs 30-day avg" },
      { label: "Incoming Shipments", value: "215", delta: "+47", trend: "up", sub: "next 14 days" },
    ],
    inventory: [
      { type: "New",  make: "Ford", model: "F-150",       stock: 186, daysOnLot: 14, price: "$43,200", status: "available" },
      { type: "New",  make: "Ford", model: "Mustang",     stock: 54,  daysOnLot: 8,  price: "$39,500", status: "available" },
      { type: "New",  make: "Ford", model: "Bronco",      stock: 41,  daysOnLot: 12, price: "$53,400", status: "available" },
      { type: "New",  make: "Ford", model: "Explorer",    stock: 92,  daysOnLot: 21, price: "$47,800", status: "available" },
      { type: "New",  make: "Ford", model: "Maverick",    stock: 73,  daysOnLot: 10, price: "$28,100", status: "available" },
      { type: "New",  make: "Ford", model: "Escape",      stock: 61,  daysOnLot: 28, price: "$32,400", status: "available" },
      { type: "New",  make: "Ford", model: "Super Duty",  stock: 48,  daysOnLot: 11, price: "$59,700", status: "available" },
      { type: "New",  make: "Ford", model: "Expedition",  stock: 29,  daysOnLot: 19, price: "$63,800", status: "available" },
      { type: "Used", make: "Ford", model: "F-150",       stock: 67,  daysOnLot: 16, price: "$35,400", status: "available" },
      { type: "Used", make: "Ford", model: "Mustang",     stock: 38,  daysOnLot: 22, price: "$32,100", status: "available" },
      { type: "New",  make: "Ford", model: "Ranger",      stock: 44,  daysOnLot: 13, price: "$37,200", status: "available" },
      { type: "Used", make: "Ford", model: "Bronco",      stock: 19,  daysOnLot: 25, price: "$44,600", status: "available" },
      { type: "New",  make: "Ford", model: "Mustang Mach-E", stock: 22, daysOnLot: 18, price: "$46,300", status: "available" },
      { type: "Used", make: "Ford", model: "Explorer",    stock: 31,  daysOnLot: 33, price: "$38,900", status: "low" },
      { type: "New",  make: "Ford", model: "Transit",     stock: 15,  daysOnLot: 39, price: "$45,200", status: "low" },
    ],
    shipments: [
      { eta: "Mar 08", model: "F-150 XLT",        qty: 42, make: "Ford", status: "confirmed" },
      { eta: "Mar 10", model: "Mustang GT",        qty: 15, make: "Ford", status: "confirmed" },
      { eta: "Mar 12", model: "Bronco Badlands",   qty: 12, make: "Ford", status: "confirmed" },
      { eta: "Mar 15", model: "Explorer ST",       qty: 18, make: "Ford", status: "in-transit" },
      { eta: "Mar 18", model: "Super Duty Lariat", qty: 22, make: "Ford", status: "in-transit" },
      { eta: "Mar 21", model: "Maverick Hybrid",   qty: 30, make: "Ford", status: "pending" },
      { eta: "Mar 24", model: "Expedition King Ranch", qty: 8, make: "Ford", status: "pending" },
    ],
    aiSummary: {
      generatedAt: "Today, 8:04 AM",
      headline: "Exceptional month — highest sales volume in 12 months.",
      insights: [
        "F-150 is flying off the lot at 14 days average — 186 units in stock with 42 more arriving Mar 8. Strong demand across all trims.",
        "Mustang sales are up 22% driven by GT and Dark Horse trims. 15 GTs incoming Mar 10 are pre-sold.",
        "Bronco continues strong at 12 days avg. 12 Badlands trims arriving Mar 12 — allocate to waitlist customers.",
        "Super Duty demand surging — 48 units at 11 days. 22 Lariats incoming should be priced at MSRP+.",
        "Overall revenue per unit up 5.1% — strongest margin month this fiscal year.",
      ],
      recommendations: [
        { tag: "Pricing", text: "With demand this strong, you have room to hold firm on pricing. Competitors are discounting but your turn rate shows you don't need to. Maintain current ASPs on F-150 and Bronco." },
        { tag: "Inventory", text: "Used Explorer stock is aging at 33 days — 31 units. With new Explorer STs arriving Mar 15, used prices will face pressure. Move 10+ used units this week." },
        { tag: "Marketing", text: "You're the #1 volume Ford dealer in LA this month. Leverage this in advertising — 'LA's #1 Ford Dealer' messaging drives trust and foot traffic." },
        { tag: "Staffing", text: "At 382 sales MTD you're averaging 19 deals/day. Consider extending Saturday hours and adding 2 temporary sales associates through month-end." },
      ],
    },
    salesTrend: {
      labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
      units:  [310, 345, 278, 352, 324, 382],
    },
    mapCenter: [34.236, -118.488],
    salesPoints: [
      { lat: 34.236, lng: -118.488, label: "Galpin Ford", sales: 382, type: "dealer" },
      { lat: 34.187, lng: -118.449, label: "Van Nuys", sales: 58 },
      { lat: 34.262, lng: -118.520, label: "Chatsworth", sales: 41 },
      { lat: 34.172, lng: -118.379, label: "Sherman Oaks", sales: 52 },
      { lat: 34.210, lng: -118.535, label: "Woodland Hills", sales: 47 },
      { lat: 34.282, lng: -118.440, label: "Granada Hills", sales: 34 },
      { lat: 34.153, lng: -118.465, label: "Encino", sales: 39 },
      { lat: 34.200, lng: -118.396, label: "Panorama City", sales: 28 },
    ],
  },

  "AutoNation Ford Torrance": {
    dealer: { name: "AutoNation Ford Torrance", location: "Torrance, CA", rooftop: "Rooftop 01" },
    stats: [
      { label: "Total Sales MTD", value: "164", delta: "+4.2%", trend: "up", sub: "vs last month" },
      { label: "Revenue MTD", value: "$4.8M", delta: "+2.9%", trend: "up", sub: "vs last month" },
      { label: "Units in Stock", value: "724", delta: "-1.5%", trend: "down", sub: "vs 30-day avg" },
      { label: "Incoming Shipments", value: "82", delta: "+11", trend: "up", sub: "next 14 days" },
    ],
    inventory: [
      { type: "New",  make: "Ford", model: "F-150",       stock: 72,  daysOnLot: 20, price: "$41,800", status: "available" },
      { type: "New",  make: "Ford", model: "Explorer",    stock: 48,  daysOnLot: 26, price: "$47,500", status: "available" },
      { type: "New",  make: "Ford", model: "Escape",      stock: 55,  daysOnLot: 32, price: "$30,900", status: "available" },
      { type: "New",  make: "Ford", model: "Bronco Sport", stock: 34, daysOnLot: 16, price: "$34,200", status: "available" },
      { type: "New",  make: "Ford", model: "Maverick",    stock: 41,  daysOnLot: 12, price: "$26,800", status: "available" },
      { type: "Used", make: "Ford", model: "F-150",       stock: 38,  daysOnLot: 24, price: "$33,500", status: "available" },
      { type: "New",  make: "Ford", model: "Mustang",     stock: 18,  daysOnLot: 14, price: "$37,600", status: "available" },
      { type: "Used", make: "Ford", model: "Explorer",    stock: 22,  daysOnLot: 41, price: "$36,200", status: "aging" },
      { type: "New",  make: "Ford", model: "Edge",        stock: 15,  daysOnLot: 48, price: "$39,800", status: "aging" },
      { type: "Used", make: "Ford", model: "Escape",      stock: 27,  daysOnLot: 37, price: "$24,700", status: "low" },
      { type: "New",  make: "Ford", model: "Super Duty",  stock: 19,  daysOnLot: 18, price: "$56,400", status: "available" },
      { type: "Used", make: "Ford", model: "Bronco",      stock: 12,  daysOnLot: 21, price: "$42,100", status: "available" },
    ],
    shipments: [
      { eta: "Mar 09", model: "F-150 Lariat",      qty: 14, make: "Ford", status: "confirmed" },
      { eta: "Mar 12", model: "Bronco Sport Big Bend", qty: 10, make: "Ford", status: "confirmed" },
      { eta: "Mar 15", model: "Escape SE",          qty: 12, make: "Ford", status: "in-transit" },
      { eta: "Mar 18", model: "Maverick XLT",       qty: 18, make: "Ford", status: "in-transit" },
      { eta: "Mar 22", model: "Explorer Limited",   qty: 8,  make: "Ford", status: "pending" },
      { eta: "Mar 25", model: "Super Duty XLT",     qty: 6,  make: "Ford", status: "pending" },
    ],
    aiSummary: {
      generatedAt: "Today, 8:04 AM",
      headline: "Steady growth but aging inventory in key segments needs action.",
      insights: [
        "F-150 performing well at 20 days avg with 72 units. 14 Lariats arriving Mar 9 will strengthen high-margin trim mix.",
        "Edge inventory is aging at 48 days — 15 units. Model is being discontinued — accelerate clearance pricing.",
        "Bronco Sport is a bright spot at 16 days. 10 Big Bends incoming Mar 12 should move quickly.",
        "Used Escape stock (27 units, 37 days) is building. Consider wholesale or auction for oldest 8–10 units.",
        "Maverick continues to be the fastest mover at 12 days avg. 18 XLTs incoming Mar 18 are well-timed.",
      ],
      recommendations: [
        { tag: "Pricing", text: "South Bay Ford is pricing F-150 at $42,500 vs. your $41,800. You're already competitive — hold pricing and focus on F&I margin instead of further discounts." },
        { tag: "Inventory", text: "Edge is discontinued. Run a 'Final Edition' clearance event this weekend. Target $2K below invoice to move all 15 units before April." },
        { tag: "Marketing", text: "Your Bronco Sport digital presence is weak compared to competitors. Invest $2K in local SEM targeting 'Bronco Sport Torrance' — search volume is up 31%." },
        { tag: "Incentive", text: "Ford is offering enhanced conquest cash on Escape for Honda CR-V and Toyota RAV4 owners. Push this to your BDC team for targeted outreach." },
      ],
    },
    salesTrend: {
      labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
      units:  [148, 161, 132, 155, 157, 164],
    },
    mapCenter: [33.840, -118.330],
    salesPoints: [
      { lat: 33.840, lng: -118.330, label: "AutoNation Ford Torrance", sales: 164, type: "dealer" },
      { lat: 33.880, lng: -118.310, label: "Torrance", sales: 42 },
      { lat: 33.862, lng: -118.399, label: "Redondo Beach", sales: 28 },
      { lat: 33.835, lng: -118.345, label: "Lomita", sales: 18 },
      { lat: 33.895, lng: -118.370, label: "Gardena", sales: 24 },
      { lat: 33.810, lng: -118.380, label: "Palos Verdes", sales: 19 },
      { lat: 33.870, lng: -118.260, label: "Carson", sales: 16 },
    ],
  },

};

let DealerData = DealerDataByAccount["South Bay Ford"];


// ============================================
//  MODEL INSIGHTS — Vehicle-level analytics
// ============================================

const ModelInsightsData = {

  vehicles: [
    {
      id: "f-150",
      model: "F-150",
      make: "Ford",
      bodyStyle: "Truck",
      type: "New",
      icon: "local_shipping",
      image: "https://upload.wikimedia.org/wikipedia/commons/3/39/Ford_F-150_Lariat_Luxury_2022.jpg",
      mtdSales: 104,
      salesDelta: "+14%",
      trend: "up",
      marketShare: "22.4%",
      avgPrice: "$42,500",
      avgPriceNum: 42500,
      avgDaysOnLot: 18,
      rating: 4.7,
      hasRecall: true,
      hasPromo: true,
      tagline: "Full-size pickup segment leader",
    },
    {
      id: "explorer",
      model: "Explorer",
      make: "Ford",
      bodyStyle: "SUV",
      type: "New",
      icon: "directions_car",
      image: "https://upload.wikimedia.org/wikipedia/commons/2/23/Ford_Explorer_%28sixth_generation%29_IMG_6063.jpg",
      mtdSales: 67,
      salesDelta: "+6%",
      trend: "up",
      marketShare: "14.1%",
      avgPrice: "$48,200",
      avgPriceNum: 48200,
      avgDaysOnLot: 24,
      rating: 4.3,
      hasRecall: false,
      hasPromo: true,
      tagline: "3-row family SUV, strong March demand",
    },
    {
      id: "mustang",
      model: "Mustang",
      make: "Ford",
      bodyStyle: "Sedan",
      type: "New",
      icon: "sports_motorsports",
      image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/2018_Ford_Mustang_GT_5.0.jpg",
      mtdSales: 31,
      salesDelta: "+22%",
      trend: "up",
      marketShare: "6.8%",
      avgPrice: "$38,900",
      avgPriceNum: 38900,
      avgDaysOnLot: 9,
      rating: 4.6,
      hasRecall: false,
      hasPromo: false,
      tagline: "Dark Horse trim driving upside",
    },
    {
      id: "bronco",
      model: "Bronco",
      make: "Ford",
      bodyStyle: "SUV",
      type: "New",
      icon: "directions_car",
      image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Ford_Bronco_%286th_generation%29_Outer_Banks_1X7A0384.jpg",
      mtdSales: 22,
      salesDelta: "+4%",
      trend: "up",
      marketShare: "4.9%",
      avgPrice: "$52,100",
      avgPriceNum: 52100,
      avgDaysOnLot: 33,
      rating: 4.5,
      hasRecall: true,
      hasPromo: false,
      tagline: "Cult following, supply-constrained",
    },
    {
      id: "maverick",
      model: "Maverick",
      make: "Ford",
      bodyStyle: "Truck",
      type: "New",
      icon: "local_shipping",
      image: "https://upload.wikimedia.org/wikipedia/commons/1/11/2025_Ford_Maverick_XLT%2C_front_4.15.25.jpg",
      mtdSales: 58,
      salesDelta: "+31%",
      trend: "up",
      marketShare: "12.1%",
      avgPrice: "$27,300",
      avgPriceNum: 27300,
      avgDaysOnLot: 14,
      rating: 4.8,
      hasRecall: false,
      hasPromo: true,
      tagline: "Compact hybrid truck — fastest mover",
    },
    {
      id: "escape",
      model: "Escape",
      make: "Ford",
      bodyStyle: "SUV",
      type: "New",
      icon: "directions_car",
      image: "https://upload.wikimedia.org/wikipedia/commons/3/35/2021_Ford_Escape_Hybrid_SEL_AWD_in_Oxford_White%2C_front_left.jpg",
      mtdSales: 43,
      salesDelta: "-9%",
      trend: "down",
      marketShare: "9.2%",
      avgPrice: "$31,600",
      avgPriceNum: 31600,
      avgDaysOnLot: 41,
      rating: 4.1,
      hasRecall: false,
      hasPromo: true,
      tagline: "Aging inventory, heavy competition",
    },
    {
      id: "mach-e",
      model: "Mustang Mach-E",
      make: "Ford",
      bodyStyle: "EV",
      type: "New",
      icon: "electric_car",
      image: "https://upload.wikimedia.org/wikipedia/commons/4/49/2021_Ford_Mustang_Mach-E_Standard_Range_Front.jpg",
      mtdSales: 16,
      salesDelta: "+48%",
      trend: "up",
      marketShare: "3.5%",
      avgPrice: "$45,800",
      avgPriceNum: 45800,
      avgDaysOnLot: 7,
      rating: 4.4,
      hasRecall: true,
      hasPromo: true,
      tagline: "EV demand accelerating after tax credit",
    },
    {
      id: "super-duty",
      model: "Super Duty",
      make: "Ford",
      bodyStyle: "Truck",
      type: "New",
      icon: "local_shipping",
      image: "https://upload.wikimedia.org/wikipedia/commons/3/35/Liberty_Public_Schools_Ford_F250%2C_MY2025.jpg",
      mtdSales: 27,
      salesDelta: "+11%",
      trend: "up",
      marketShare: "5.7%",
      avgPrice: "$58,300",
      avgPriceNum: 58300,
      avgDaysOnLot: 15,
      rating: 4.6,
      hasRecall: false,
      hasPromo: false,
      tagline: "Heavy-duty, commercial fleet demand",
    },
    {
      id: "navigator",
      model: "Navigator",
      make: "Lincoln",
      bodyStyle: "SUV",
      type: "New",
      icon: "directions_car",
      image: "https://upload.wikimedia.org/wikipedia/commons/1/1f/2019_Lincoln_Navigator_%27Reserve%27%2C_front_8.29.20.jpg",
      mtdSales: 11,
      salesDelta: "-12%",
      trend: "down",
      marketShare: "2.4%",
      avgPrice: "$82,400",
      avgPriceNum: 82400,
      avgDaysOnLot: 42,
      rating: 4.2,
      hasRecall: false,
      hasPromo: true,
      tagline: "Luxury full-size — pricing pressure",
    },
    {
      id: "aviator",
      model: "Aviator",
      make: "Lincoln",
      bodyStyle: "SUV",
      type: "New",
      icon: "directions_car",
      image: "https://upload.wikimedia.org/wikipedia/commons/8/81/2020_Lincoln_Aviator_Black_Label_in_Chroma_Caviar_Dark_Grey%2C_front_left.jpg",
      mtdSales: 28,
      salesDelta: "+3%",
      trend: "flat",
      marketShare: "6.1%",
      avgPrice: "$58,900",
      avgPriceNum: 58900,
      avgDaysOnLot: 31,
      rating: 4.5,
      hasRecall: false,
      hasPromo: true,
      tagline: "Top Lincoln performer, steady demand",
    },
    {
      id: "transit",
      model: "Transit",
      make: "Ford",
      bodyStyle: "Van",
      type: "New",
      icon: "airport_shuttle",
      image: "https://upload.wikimedia.org/wikipedia/commons/8/88/2016_Ford_Transit_350_2.2.jpg",
      mtdSales: 9,
      salesDelta: "-4%",
      trend: "down",
      marketShare: "1.9%",
      avgPrice: "$44,900",
      avgPriceNum: 44900,
      avgDaysOnLot: 62,
      rating: 4.2,
      hasRecall: false,
      hasPromo: false,
      tagline: "Commercial van — niche demand",
    },
    {
      id: "ranger",
      model: "Ranger",
      make: "Ford",
      bodyStyle: "Truck",
      type: "New",
      icon: "local_shipping",
      image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Ford_Ranger_%28T6%2C_P703%29_Wildtrak_IMG_7320.jpg",
      mtdSales: 38,
      salesDelta: "+9%",
      trend: "up",
      marketShare: "8.1%",
      avgPrice: "$36,700",
      avgPriceNum: 36700,
      avgDaysOnLot: 12,
      rating: 4.4,
      hasRecall: false,
      hasPromo: true,
      tagline: "Mid-size truck, Raptor edition hot",
    },
  ],

  details: {
    "f-150": {
      id: "f-150",
      model: "F-150",
      make: "Ford",
      icon: "local_shipping",
      bodyStyle: "Full-Size Pickup",
      year: "2026",
      priceRange: "$38,500 – $79,200",
      trims: ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Raptor"],
      rating: 4.7,
      reviewCount: 4829,
      stats: [
        { label: "Total Sales MTD", value: "104", delta: "+14%", trend: "up", sub: "vs last month" },
        { label: "Market Share", value: "22.4%", delta: "+1.8 pts", trend: "up", sub: "segment leader" },
        { label: "Avg Days on Lot", value: "18d", delta: "-3d", trend: "up", sub: "faster than avg" },
        { label: "Revenue MTD", value: "$4.42M", delta: "+9.2%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [87, 92, 78, 95, 98, 104],
      },
      competitors: [
        { name: "Silverado 1500", make: "Chevrolet", sales: 89, share: 19.1, price: "$41,900", delta: "+7%", trend: "up" },
        { name: "Ram 1500",       make: "Ram",       sales: 76, share: 16.3, price: "$44,200", delta: "-2%", trend: "down" },
        { name: "Tundra",         make: "Toyota",    sales: 42, share: 9.0,  price: "$46,800", delta: "+4%", trend: "up" },
        { name: "Sierra 1500",    make: "GMC",       sales: 38, share: 8.2,  price: "$45,100", delta: "+1%", trend: "up" },
        { name: "Titan",          make: "Nissan",    sales: 12, share: 2.6,  price: "$39,400", delta: "-11%", trend: "down" },
      ],
      promotions: [
        { title: "0% APR for 60 months",         type: "Financing", validUntil: "Mar 31, 2026", applicable: "XLT & Lariat trims",   impact: "high" },
        { title: "$2,500 Cashback Bonus",        type: "Rebate",    validUntil: "Mar 31, 2026", applicable: "All new 2026 F-150",    impact: "medium" },
        { title: "Military Appreciation $500",   type: "Loyalty",   validUntil: "Apr 15, 2026", applicable: "All trims",             impact: "low" },
      ],
      recalls: [
        { id: "25V-412", title: "Rearview Camera Image Delay",      severity: "moderate", affected: "2024–2025 F-150 models",      status: "open",     announced: "Jan 18, 2026" },
        { id: "24V-887", title: "Seat Belt Pretensioner Assembly",  severity: "low",      affected: "2023 F-150 SuperCrew",        status: "resolved", announced: "Nov 2, 2025" },
      ],
      demographics: [
        { label: "Age 35–54", pct: 46 },
        { label: "Age 55+",   pct: 31 },
        { label: "Age 25–34", pct: 18 },
        { label: "Age 18–24", pct: 5  },
      ],
      searchInterest: { delta: "+28%", trend: "up", sub: "vs last 30 days (Google Trends)" },
      aiHeadline: "F-150 is dominating your market — lean into premium trims before Silverado catches up.",
      aiInsights: [
        "Your F-150 sales are up 14% MTD while Silverado is trailing. Hold firm on MSRP for XLT and Lariat trims.",
        "Raptor and Platinum trims are moving in 11 days — consider reallocating showroom floor space to spotlight high-margin trims.",
        "Active recall 25V-412 affects ~8% of current inventory. Prioritize fix scheduling to avoid customer friction.",
        "Ram 1500 is down 2% and Nissan Titan down 11% — conquest these shoppers with the $2,500 cashback offer.",
      ],
    },

    "explorer": {
      id: "explorer",
      model: "Explorer",
      make: "Ford",
      icon: "directions_car",
      bodyStyle: "3-Row Mid-Size SUV",
      year: "2026",
      priceRange: "$38,200 – $58,600",
      trims: ["Active", "ST-Line", "Platinum", "ST", "King Ranch"],
      rating: 4.3,
      reviewCount: 2104,
      stats: [
        { label: "Total Sales MTD", value: "67", delta: "+6%", trend: "up", sub: "vs last month" },
        { label: "Market Share", value: "14.1%", delta: "+0.4 pts", trend: "up", sub: "2nd in segment" },
        { label: "Avg Days on Lot", value: "24d", delta: "-2d", trend: "up", sub: "improving" },
        { label: "Revenue MTD", value: "$3.23M", delta: "+5.1%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [54, 59, 48, 61, 63, 67],
      },
      competitors: [
        { name: "Telluride",     make: "Kia",      sales: 71, share: 15.0, price: "$45,800", delta: "+9%",  trend: "up" },
        { name: "Grand Cherokee", make: "Jeep",     sales: 58, share: 12.2, price: "$49,200", delta: "+3%",  trend: "up" },
        { name: "Palisade",      make: "Hyundai",  sales: 52, share: 11.0, price: "$44,100", delta: "+12%", trend: "up" },
        { name: "Pilot",         make: "Honda",    sales: 48, share: 10.1, price: "$42,900", delta: "-5%",  trend: "down" },
      ],
      promotions: [
        { title: "$1,500 Conquest Cash",       type: "Rebate",    validUntil: "Mar 31, 2026", applicable: "Honda / Toyota owners", impact: "high" },
        { title: "1.9% APR for 48 months",     type: "Financing", validUntil: "Mar 31, 2026", applicable: "ST-Line & Platinum",    impact: "medium" },
      ],
      recalls: [],
      demographics: [
        { label: "Age 35–54", pct: 58 },
        { label: "Age 55+",   pct: 22 },
        { label: "Age 25–34", pct: 16 },
        { label: "Age 18–24", pct: 4  },
      ],
      searchInterest: { delta: "+11%", trend: "up", sub: "vs last 30 days" },
      aiHeadline: "Explorer is stable but losing ground to Kia Telluride. Act on conquest cash now.",
      aiInsights: [
        "Telluride outsold you by 4 units this month. Their pricing is $3.6K higher — your $1,500 conquest cash closes the perceived value gap.",
        "Explorer ST-Line demand is up 22% on your site. Prioritize incoming shipment on Mar 11 for waitlisted leads.",
        "No active recalls — a trust advantage over Grand Cherokee (2 open recalls this quarter).",
        "Family SUV searches peak on weekends in your zip codes — boost SEM budget Thu–Sat.",
      ],
    },

    "mustang": {
      id: "mustang",
      model: "Mustang",
      make: "Ford",
      icon: "sports_motorsports",
      bodyStyle: "Sports Coupe",
      year: "2026",
      priceRange: "$32,800 – $69,500",
      trims: ["EcoBoost", "GT", "Dark Horse", "Shelby GT500"],
      rating: 4.6,
      reviewCount: 1876,
      stats: [
        { label: "Total Sales MTD", value: "31", delta: "+22%", trend: "up", sub: "vs last month" },
        { label: "Market Share", value: "6.8%", delta: "+1.2 pts", trend: "up", sub: "category leader" },
        { label: "Avg Days on Lot", value: "9d", delta: "-4d", trend: "up", sub: "fastest mover" },
        { label: "Revenue MTD", value: "$1.21M", delta: "+18%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [18, 22, 14, 21, 25, 31],
      },
      competitors: [
        { name: "Camaro",   make: "Chevrolet", sales: 8,  share: 1.7, price: "$36,900", delta: "-48%", trend: "down" },
        { name: "Challenger", make: "Dodge",   sales: 0,  share: 0,   price: "$38,400", delta: "-100%", trend: "down" },
        { name: "GR Supra", make: "Toyota",    sales: 14, share: 3.1, price: "$47,200", delta: "-3%",  trend: "down" },
        { name: "BRZ",      make: "Subaru",    sales: 11, share: 2.4, price: "$31,400", delta: "+2%",  trend: "up" },
      ],
      promotions: [],
      recalls: [],
      demographics: [
        { label: "Age 25–34", pct: 41 },
        { label: "Age 35–54", pct: 33 },
        { label: "Age 18–24", pct: 15 },
        { label: "Age 55+",   pct: 11 },
      ],
      searchInterest: { delta: "+42%", trend: "up", sub: "Dark Horse trim driving spike" },
      aiHeadline: "With Camaro and Challenger discontinued, Mustang owns the muscle-car segment.",
      aiInsights: [
        "You're the last American muscle car standing. Competitors have exited — this is a generational opportunity.",
        "Dark Horse trim search interest is up 76% YoY. Your 3 incoming units should be pre-sold before arrival.",
        "Young buyer share (18–34) is 56% for Mustang vs. 22% market avg. Lean into social + influencer marketing.",
        "Zero active promotions needed — hold MSRP and focus on F&I margin from financing bundle.",
      ],
    },

    "bronco": {
      id: "bronco",
      model: "Bronco",
      make: "Ford",
      icon: "directions_car",
      bodyStyle: "Off-Road SUV",
      year: "2026",
      priceRange: "$41,900 – $72,800",
      trims: ["Big Bend", "Black Diamond", "Outer Banks", "Badlands", "Wildtrak", "Raptor"],
      rating: 4.5,
      reviewCount: 3412,
      stats: [
        { label: "Total Sales MTD", value: "22", delta: "+4%", trend: "up", sub: "vs last month" },
        { label: "Market Share", value: "4.9%", delta: "+0.1 pts", trend: "flat", sub: "supply-limited" },
        { label: "Avg Days on Lot", value: "33d", delta: "+5d", trend: "down", sub: "customer waits" },
        { label: "Revenue MTD", value: "$1.15M", delta: "+6%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [24, 28, 19, 22, 21, 22],
      },
      competitors: [
        { name: "Wrangler",    make: "Jeep",     sales: 64, share: 13.8, price: "$46,800", delta: "-8%",  trend: "down" },
        { name: "4Runner",     make: "Toyota",   sales: 51, share: 10.9, price: "$52,300", delta: "+15%", trend: "up" },
        { name: "Defender 90", make: "Land Rover", sales: 8, share: 1.7, price: "$74,100", delta: "+4%",  trend: "up" },
      ],
      promotions: [],
      recalls: [
        { id: "25V-188", title: "Hardtop Retention Clip Failure", severity: "moderate", affected: "2023–2024 Bronco 2-Door", status: "open", announced: "Feb 9, 2026" },
      ],
      demographics: [
        { label: "Age 35–54", pct: 48 },
        { label: "Age 25–34", pct: 29 },
        { label: "Age 55+",   pct: 18 },
        { label: "Age 18–24", pct: 5  },
      ],
      searchInterest: { delta: "+19%", trend: "up", sub: "outdoor enthusiast segment" },
      aiHeadline: "Bronco is supply-constrained, not demand-constrained. Allocate inbound units to wait list.",
      aiInsights: [
        "Wrangler is down 8% — capture their off-road shoppers with Badlands trim demos at weekend events.",
        "Toyota 4Runner is surging 15% but priced $300 higher. Match their financing offer to defend share.",
        "Active recall on hardtop clips may slow delivery. Communicate proactively with customers awaiting delivery.",
        "Bronco resale values are 8% above MSRP — promote this to close hesitant buyers worried about depreciation.",
      ],
    },

    "maverick": {
      id: "maverick",
      model: "Maverick",
      make: "Ford",
      icon: "local_shipping",
      bodyStyle: "Compact Pickup",
      year: "2026",
      priceRange: "$24,500 – $38,100",
      trims: ["XL", "XLT", "Lariat", "Tremor", "Lobo"],
      rating: 4.8,
      reviewCount: 2687,
      stats: [
        { label: "Total Sales MTD", value: "58", delta: "+31%", trend: "up", sub: "vs last month" },
        { label: "Market Share", value: "12.1%", delta: "+2.4 pts", trend: "up", sub: "category creator" },
        { label: "Avg Days on Lot", value: "14d", delta: "-6d", trend: "up", sub: "fastest Ford turn" },
        { label: "Revenue MTD", value: "$1.58M", delta: "+26%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [34, 41, 32, 46, 44, 58],
      },
      competitors: [
        { name: "Santa Cruz", make: "Hyundai", sales: 22, share: 4.7, price: "$29,400", delta: "+7%",  trend: "up" },
      ],
      promotions: [
        { title: "Hybrid Model Fuel Credit",  type: "Incentive", validUntil: "Mar 31, 2026", applicable: "Hybrid trims", impact: "medium" },
      ],
      recalls: [],
      demographics: [
        { label: "Age 25–34", pct: 38 },
        { label: "Age 35–54", pct: 34 },
        { label: "Age 18–24", pct: 19 },
        { label: "Age 55+",   pct: 9  },
      ],
      searchInterest: { delta: "+54%", trend: "up", sub: "highest in Ford lineup" },
      aiHeadline: "Maverick owns the compact-truck segment. Only Santa Cruz competes, and you outsell them 2.6:1.",
      aiInsights: [
        "You're selling Mavericks faster than you can stock them. Advocate for increased factory allocation next quarter.",
        "Hybrid trim is 71% of your Maverick volume — prioritize inbound hybrid allocation.",
        "Young buyer share (57%) is the highest in your lineup. Maverick is a gateway to the Ford brand for Gen Z.",
        "Santa Cruz demand is rising — but your fuel efficiency story is stronger. Push hybrid MPG in ad creative.",
      ],
    },

    "escape": {
      id: "escape",
      model: "Escape",
      make: "Ford",
      icon: "directions_car",
      bodyStyle: "Compact Crossover",
      year: "2026",
      priceRange: "$29,400 – $41,800",
      trims: ["Active", "ST-Line", "Platinum", "Plug-In Hybrid"],
      rating: 4.1,
      reviewCount: 1944,
      stats: [
        { label: "Total Sales MTD", value: "43", delta: "-9%", trend: "down", sub: "vs last month" },
        { label: "Market Share", value: "9.2%", delta: "-1.3 pts", trend: "down", sub: "losing share" },
        { label: "Avg Days on Lot", value: "41d", delta: "+8d", trend: "down", sub: "aging fast" },
        { label: "Revenue MTD", value: "$1.36M", delta: "-7.4%", trend: "down", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [56, 52, 49, 48, 47, 43],
      },
      competitors: [
        { name: "CR-V",    make: "Honda",    sales: 94, share: 20.1, price: "$32,800", delta: "+3%",  trend: "up" },
        { name: "RAV4",    make: "Toyota",   sales: 108, share: 23.1, price: "$33,400", delta: "+5%",  trend: "up" },
        { name: "Tucson",  make: "Hyundai",  sales: 61, share: 13.0, price: "$31,200", delta: "+11%", trend: "up" },
        { name: "Sportage", make: "Kia",     sales: 48, share: 10.2, price: "$30,900", delta: "+7%",  trend: "up" },
      ],
      promotions: [
        { title: "$3,000 Customer Cash",     type: "Rebate",    validUntil: "Mar 31, 2026", applicable: "All 2026 Escape",       impact: "high" },
        { title: "0% APR for 72 months",     type: "Financing", validUntil: "Mar 31, 2026", applicable: "Active & ST-Line",      impact: "high" },
        { title: "Plug-In $7,500 Tax Credit", type: "Government", validUntil: "Ongoing",     applicable: "Plug-In Hybrid",        impact: "medium" },
      ],
      recalls: [],
      demographics: [
        { label: "Age 35–54", pct: 42 },
        { label: "Age 25–34", pct: 28 },
        { label: "Age 55+",   pct: 24 },
        { label: "Age 18–24", pct: 6  },
      ],
      searchInterest: { delta: "-12%", trend: "down", sub: "category softening" },
      aiHeadline: "Escape is under pressure from Japanese rivals. Stack incentives or accept aging inventory.",
      aiInsights: [
        "RAV4 outsells Escape 2.5:1 in your market. Your existing $3K cash + 0% APR stack is competitive — promote it aggressively.",
        "Average days on lot hit 41 — above the 35-day warning threshold. Target 8–10 units for wholesale disposition.",
        "Plug-In Hybrid trim benefits from the $7,500 tax credit. This is your best closing tool — most reps aren't mentioning it.",
        "Consider a dealer-funded $500 trade-assist bump to clear 2025 leftover stock before 2026 deliveries arrive.",
      ],
    },

    "mach-e": {
      id: "mach-e",
      model: "Mustang Mach-E",
      make: "Ford",
      icon: "electric_car",
      bodyStyle: "Electric Crossover",
      year: "2026",
      priceRange: "$42,100 – $63,800",
      trims: ["Select", "Premium", "California Route 1", "GT"],
      rating: 4.4,
      reviewCount: 1521,
      stats: [
        { label: "Total Sales MTD", value: "16", delta: "+48%", trend: "up", sub: "vs last month" },
        { label: "Market Share", value: "3.5%", delta: "+1.1 pts", trend: "up", sub: "EV segment" },
        { label: "Avg Days on Lot", value: "7d", delta: "-12d", trend: "up", sub: "fastest in lineup" },
        { label: "Revenue MTD", value: "$733K", delta: "+44%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [6, 8, 7, 9, 11, 16],
      },
      competitors: [
        { name: "Model Y",     make: "Tesla",    sales: 124, share: 26.5, price: "$44,200", delta: "+2%",  trend: "up" },
        { name: "IONIQ 5",     make: "Hyundai",  sales: 29,  share: 6.2,  price: "$43,800", delta: "+18%", trend: "up" },
        { name: "EV6",         make: "Kia",      sales: 18,  share: 3.9,  price: "$45,100", delta: "+12%", trend: "up" },
        { name: "ID.4",        make: "VW",       sales: 12,  share: 2.6,  price: "$42,700", delta: "-4%",  trend: "down" },
      ],
      promotions: [
        { title: "$7,500 Federal Tax Credit",     type: "Government", validUntil: "Ongoing",        applicable: "All trims",      impact: "high" },
        { title: "Complimentary Home Charger",    type: "Incentive",  validUntil: "Mar 31, 2026",   applicable: "Premium & up",   impact: "medium" },
        { title: "2 Years Free Supercharging",    type: "Incentive",  validUntil: "Mar 31, 2026",   applicable: "All trims",      impact: "high" },
      ],
      recalls: [
        { id: "25V-301", title: "High-Voltage Battery Contactor",    severity: "high",     affected: "2023–2024 Mach-E GT",      status: "open",     announced: "Feb 22, 2026" },
      ],
      demographics: [
        { label: "Age 35–54", pct: 51 },
        { label: "Age 25–34", pct: 28 },
        { label: "Age 55+",   pct: 16 },
        { label: "Age 18–24", pct: 5  },
      ],
      searchInterest: { delta: "+67%", trend: "up", sub: "post tax-credit boost" },
      aiHeadline: "Mach-E is your hottest EV. Tax credit + free charging = closable deal, but watch the GT recall.",
      aiInsights: [
        "16 units sold MTD is your best-ever Mach-E month. All stock is moving in under a week — advocate for double allocation.",
        "Open recall on GT trim contactor is high-severity. Pause GT deliveries until remedy is applied. Communicate status to customers.",
        "Tesla Model Y dominates EV share at 26.5% but their direct-sales model frustrates some shoppers. Position your test drive and trade-in flexibility as differentiators.",
        "IONIQ 5 is rising fast (+18%). Match their battery warranty messaging in your ads.",
      ],
    },

    "super-duty": {
      id: "super-duty",
      model: "Super Duty",
      make: "Ford",
      icon: "local_shipping",
      bodyStyle: "Heavy-Duty Pickup",
      year: "2026",
      priceRange: "$48,200 – $98,500",
      trims: ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited"],
      rating: 4.6,
      reviewCount: 1287,
      stats: [
        { label: "Total Sales MTD", value: "27", delta: "+11%", trend: "up", sub: "vs last month" },
        { label: "Market Share", value: "5.7%", delta: "+0.5 pts", trend: "up", sub: "HD segment" },
        { label: "Avg Days on Lot", value: "15d", delta: "-2d", trend: "up", sub: "commercial demand" },
        { label: "Revenue MTD", value: "$1.57M", delta: "+13%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [19, 22, 18, 24, 24, 27],
      },
      competitors: [
        { name: "Silverado HD", make: "Chevrolet", sales: 21, share: 4.5, price: "$56,800", delta: "+4%",  trend: "up" },
        { name: "Ram HD",       make: "Ram",       sales: 18, share: 3.9, price: "$58,900", delta: "-7%",  trend: "down" },
        { name: "Sierra HD",    make: "GMC",       sales: 9,  share: 1.9, price: "$59,400", delta: "+1%",  trend: "flat" },
      ],
      promotions: [],
      recalls: [],
      demographics: [
        { label: "Age 35–54", pct: 52 },
        { label: "Age 55+",   pct: 34 },
        { label: "Age 25–34", pct: 12 },
        { label: "Age 18–24", pct: 2  },
      ],
      searchInterest: { delta: "+9%", trend: "up", sub: "commercial fleet inquiries" },
      aiHeadline: "Super Duty is quietly dominating HD. Commercial fleet is 40% of volume — target business buyers.",
      aiInsights: [
        "Ram HD is down 7% — use this to conquest their commercial customers with fleet-pricing sell sheets.",
        "No active promotions needed. HD buyers are practical and price-is-function; focus on total cost of ownership.",
        "Average transaction price is $62,400, the highest in your lineup. Upsell Lariat → Platinum nets +$5,800 per unit.",
        "Commercial DOT inspection season begins April 1 — expect fleet replacement surge next month.",
      ],
    },

    "navigator": {
      id: "navigator",
      model: "Navigator",
      make: "Lincoln",
      icon: "directions_car",
      bodyStyle: "Full-Size Luxury SUV",
      year: "2026",
      priceRange: "$80,800 – $122,500",
      trims: ["Standard", "Reserve", "Black Label", "Navigator L"],
      rating: 4.2,
      reviewCount: 612,
      stats: [
        { label: "Total Sales MTD", value: "11", delta: "-12%", trend: "down", sub: "vs last month" },
        { label: "Market Share", value: "2.4%", delta: "-0.3 pts", trend: "down", sub: "luxury HD" },
        { label: "Avg Days on Lot", value: "42d", delta: "+7d", trend: "down", sub: "aging" },
        { label: "Revenue MTD", value: "$906K", delta: "-9%", trend: "down", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [14, 18, 12, 15, 12, 11],
      },
      competitors: [
        { name: "Escalade",     make: "Cadillac", sales: 28, share: 6.0, price: "$88,100", delta: "+2%",  trend: "up" },
        { name: "Yukon Denali", make: "GMC",      sales: 31, share: 6.6, price: "$78,400", delta: "+6%",  trend: "up" },
        { name: "Wagoneer",     make: "Jeep",     sales: 22, share: 4.7, price: "$76,500", delta: "+14%", trend: "up" },
      ],
      promotions: [
        { title: "$5,000 Lincoln Access Cash", type: "Rebate",    validUntil: "Mar 31, 2026", applicable: "Reserve & Black Label", impact: "high" },
        { title: "Complimentary Chauffeur Service", type: "Incentive", validUntil: "Apr 30, 2026", applicable: "Black Label", impact: "medium" },
      ],
      recalls: [],
      demographics: [
        { label: "Age 55+",   pct: 44 },
        { label: "Age 35–54", pct: 41 },
        { label: "Age 25–34", pct: 13 },
        { label: "Age 18–24", pct: 2  },
      ],
      searchInterest: { delta: "-5%", trend: "down", sub: "luxury SUV demand softening" },
      aiHeadline: "Navigator is losing ground to Escalade and Yukon Denali. Aggressive incentive stacking required.",
      aiInsights: [
        "Escalade outsells Navigator 2.5:1 here. Cadillac has better brand momentum — your $5K Access Cash alone won't close the gap.",
        "Consider an additional dealer-funded $3K incentive on aging Navigator L units — 4 units past 55 days.",
        "Black Label service perks are under-marketed. Promote the chauffeur program in your top-10 CRM segment (HHI $500K+).",
        "Wagoneer is gaining 14% — they're winning price-conscious luxury buyers. Navigator needs to defend at Reserve trim.",
      ],
    },

    "aviator": {
      id: "aviator",
      model: "Aviator",
      make: "Lincoln",
      icon: "directions_car",
      bodyStyle: "3-Row Luxury SUV",
      year: "2026",
      priceRange: "$56,400 – $87,900",
      trims: ["Standard", "Reserve", "Grand Touring", "Black Label"],
      rating: 4.5,
      reviewCount: 874,
      stats: [
        { label: "Total Sales MTD", value: "28", delta: "+3%", trend: "flat", sub: "vs last month" },
        { label: "Market Share", value: "6.1%", delta: "+0.2 pts", trend: "up", sub: "luxury 3-row" },
        { label: "Avg Days on Lot", value: "31d", delta: "-3d", trend: "up", sub: "vs 30-day avg" },
        { label: "Revenue MTD", value: "$1.65M", delta: "+4%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [22, 25, 19, 27, 27, 28],
      },
      competitors: [
        { name: "XT6",       make: "Cadillac", sales: 19, share: 4.0, price: "$54,800", delta: "+1%", trend: "flat" },
        { name: "X5",        make: "BMW",      sales: 42, share: 9.0, price: "$68,200", delta: "+5%", trend: "up" },
        { name: "MDX",       make: "Acura",    sales: 31, share: 6.6, price: "$54,100", delta: "+8%", trend: "up" },
        { name: "Ascent Touring", make: "Subaru", sales: 14, share: 3.0, price: "$49,400", delta: "-2%", trend: "down" },
      ],
      promotions: [
        { title: "$2,000 Lincoln Loyalty Cash", type: "Loyalty",   validUntil: "Mar 31, 2026", applicable: "Current Lincoln owners", impact: "medium" },
        { title: "1.9% APR for 60 months",      type: "Financing", validUntil: "Mar 31, 2026", applicable: "Reserve & Grand Touring", impact: "high" },
      ],
      recalls: [],
      demographics: [
        { label: "Age 35–54", pct: 49 },
        { label: "Age 55+",   pct: 36 },
        { label: "Age 25–34", pct: 13 },
        { label: "Age 18–24", pct: 2  },
      ],
      searchInterest: { delta: "+14%", trend: "up", sub: "holding momentum" },
      aiHeadline: "Aviator is your Lincoln workhorse. BMW X5 is the real battle — win on price.",
      aiInsights: [
        "BMW X5 is your biggest threat at 42 units vs. your 28. X5 is priced $11.8K higher — lean into value messaging.",
        "Acura MDX is gaining 8% on price-conscious luxury shoppers. Reserve trim + 1.9% APR is your counter-move.",
        "Loyalty cash drives 18% of Aviator deals — CRM pull list of 2019–2020 MKX owners should receive direct outreach.",
        "Black Label allocation is critical — you've lost 3 deals in 60 days due to BL stockouts.",
      ],
    },

    "transit": {
      id: "transit",
      model: "Transit",
      make: "Ford",
      icon: "airport_shuttle",
      bodyStyle: "Commercial Van",
      year: "2026",
      priceRange: "$42,800 – $68,400",
      trims: ["Cargo", "Passenger", "Crew", "E-Transit"],
      rating: 4.2,
      reviewCount: 514,
      stats: [
        { label: "Total Sales MTD", value: "9", delta: "-4%", trend: "down", sub: "vs last month" },
        { label: "Market Share", value: "1.9%", delta: "-0.2 pts", trend: "down", sub: "commercial van" },
        { label: "Avg Days on Lot", value: "62d", delta: "+14d", trend: "down", sub: "aging" },
        { label: "Revenue MTD", value: "$404K", delta: "-6%", trend: "down", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [12, 14, 8, 11, 9, 9],
      },
      competitors: [
        { name: "Sprinter",        make: "Mercedes", sales: 14, share: 3.0, price: "$58,700", delta: "+2%",  trend: "up" },
        { name: "ProMaster",       make: "Ram",      sales: 7,  share: 1.5, price: "$46,200", delta: "-3%",  trend: "down" },
        { name: "NV200",           make: "Nissan",   sales: 3,  share: 0.6, price: "$34,800", delta: "-18%", trend: "down" },
      ],
      promotions: [],
      recalls: [],
      demographics: [
        { label: "Commercial / Fleet",  pct: 82 },
        { label: "Consumer (Adventure)", pct: 13 },
        { label: "Government / Muni",   pct: 5  },
      ],
      searchInterest: { delta: "-3%", trend: "down", sub: "fleet buyer cycles" },
      aiHeadline: "Transit is a B2B story. Retail demand is thin — focus sales energy on commercial fleet pipeline.",
      aiInsights: [
        "62 days on lot is a red flag. Consider wholesale auction for 2–3 oldest units to reset floor.",
        "Sprinter outsells Transit here because of brand prestige. Compete on upfit flexibility, not badge.",
        "E-Transit variant qualifies for commercial clean vehicle credit (up to $7,500). Most SMB fleets don't know this — lead with that in outreach.",
        "Launch a commercial sales day this Saturday — invite your 20 top local business accounts with dedicated finance.",
      ],
    },

    "ranger": {
      id: "ranger",
      model: "Ranger",
      make: "Ford",
      icon: "local_shipping",
      bodyStyle: "Mid-Size Pickup",
      year: "2026",
      priceRange: "$32,400 – $56,900",
      trims: ["XL", "XLT", "Lariat", "Tremor", "Raptor"],
      rating: 4.4,
      reviewCount: 1098,
      stats: [
        { label: "Total Sales MTD", value: "38", delta: "+9%", trend: "up", sub: "vs last month" },
        { label: "Market Share", value: "8.1%", delta: "+0.6 pts", trend: "up", sub: "mid-size truck" },
        { label: "Avg Days on Lot", value: "12d", delta: "-4d", trend: "up", sub: "strong turn" },
        { label: "Revenue MTD", value: "$1.39M", delta: "+11%", trend: "up", sub: "vs last month" },
      ],
      salesHistory: {
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        units: [26, 29, 22, 31, 35, 38],
      },
      competitors: [
        { name: "Tacoma",    make: "Toyota",   sales: 84, share: 17.9, price: "$38,900", delta: "+9%", trend: "up" },
        { name: "Colorado",  make: "Chevrolet", sales: 41, share: 8.8,  price: "$36,100", delta: "+4%", trend: "up" },
        { name: "Frontier",  make: "Nissan",   sales: 22, share: 4.7,  price: "$33,400", delta: "-2%", trend: "down" },
        { name: "Canyon",    make: "GMC",      sales: 14, share: 3.0,  price: "$38,500", delta: "+7%", trend: "up" },
      ],
      promotions: [
        { title: "$1,500 Trade-In Bonus",    type: "Rebate", validUntil: "Mar 31, 2026", applicable: "All 2026 Ranger", impact: "medium" },
      ],
      recalls: [],
      demographics: [
        { label: "Age 25–34", pct: 35 },
        { label: "Age 35–54", pct: 38 },
        { label: "Age 55+",   pct: 19 },
        { label: "Age 18–24", pct: 8  },
      ],
      searchInterest: { delta: "+22%", trend: "up", sub: "Raptor variant leading" },
      aiHeadline: "Ranger Raptor is pulling the lineup. Tacoma is still #1 — flank on price, not power.",
      aiInsights: [
        "Raptor trim is 31% of Ranger volume. Prioritize Raptor allocation over base XL.",
        "Tacoma leads the segment but your Raptor offers more HP per dollar. Push spec comparisons in ads.",
        "$1,500 trade bonus is underused — only 6 reps have closed with it this week. Re-train on conquest trade scripts.",
        "Ranger search interest is up 22% — invest in a Raptor off-road demo event next weekend.",
      ],
    },
  },
};

