//>>built
/*
 text 2.0.16 Copyright jQuery Foundation and other contributors.
 Released under MIT license, http://github.com/requirejs/text/LICENSE
*/
(function(a,c){var h=function(){return"undefined"!==typeof z?z:"undefined"!==typeof window?window:"undefined"!==typeof self?self:this}(),f=function(){},g=function(b){for(var d in b)return 0;return 1},v={}.toString,t=function(b){return"[object Function]"==v.call(b)},u=function(b){return"[object String]"==v.call(b)},D=function(b){return"[object Array]"==v.call(b)},p=function(b,d){if(b)for(var k=0;k<b.length;)d(b[k++])},m=function(b,d){for(var k in d)b[k]=d[k];return b},q=function(b,d){return m(Error(b),
{src:"dojoLoader",info:d})},da=1,F=function(){return"_"+da++},l=function(b,d,k){return wa(b,d,k,0,l)},z=h,e=z.document,Qa=e&&e.createElement("DiV"),n=l.has=function(b){return t(r[b])?r[b]=r[b](z,e,Qa):r[b]},r=n.cache=c.hasCache;t(a)&&(a=a(h));n.add=function(b,d,k,x){(void 0===r[b]||x)&&(r[b]=d);return k&&n(b)};n.add("host-webworker","undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope);n("host-webworker")&&(m(c.hasCache,{"host-browser":0,dom:0,"dojo-dom-ready-api":0,"dojo-sniff":0,
"dojo-inject-api":1,"host-webworker":1}),c.loaderPatch={injectUrl:function(b,d){try{importScripts(b),d()}catch(k){console.info("failed to load resource ("+b+")"),console.error(k)}}});for(var O in a.has)n.add(O,a.has[O],0,1);l.async=1;var ea=new Function("return eval(arguments[0]);");l.eval=function(b,d){return ea(b+"\r\n//# sourceURL\x3d"+d)};var fa={},G=l.signal=function(b,d){b=fa[b];p(b&&b.slice(0),function(b){b.apply(null,D(d)?d:[d])})},Ra=l.on=function(b,d){var k=fa[b]||(fa[b]=[]);k.push(d);return{remove:function(){for(var b=
0;b<k.length;b++)if(k[b]===d){k.splice(b,1);break}}}},xa=[],Sa={},ya=[],H={},za=l.map={},P=[],w={},ha="",I={},Q={},R={},J=0,T=function(b){var d,k;for(d in Q){var x=Q[d];if(k=d.match(/^url:(.+)/))I["url:"+Aa(k[1],b)]=x;else if("*now"==d)var a=x;else"*noref"!=d&&(k=S(d,b,!0),I[k.mid]=I["url:"+k.url]=x)}a&&a(ia(b));Q={}},Ca=function(b){return b.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(b){return"\\"+b})},ja=function(b,d){d.splice(0,d.length);for(var k in b)d.push([k,b[k],new RegExp("^"+Ca(k)+"(/|$)"),
k.length]);d.sort(function(b,d){return d[3]-b[3]});return d},Ta=function(b,d){p(b,function(b){d.push([u(b[0])?new RegExp("^"+Ca(b[0])+"$"):b[0],b[1]])})},Da=function(b){var d=b.name;d||(d=b,b={name:d});b=m({main:"main"},b);b.location=b.location?b.location:d;b.packageMap&&(za[d]=b.packageMap);b.main.indexOf("./")||(b.main=b.main.substring(2));H[d]=b},Ea=[],L=function(b,d,k){for(var a in b){"waitSeconds"==a&&(l.waitms=1E3*(b[a]||0));"cacheBust"==a&&(ha=b[a]?u(b[a])?b[a]:(new Date).getTime()+"":"");
if("baseUrl"==a||"combo"==a)l[a]=b[a];b[a]!==r&&(l.rawConfig[a]=b[a],"has"!=a&&n.add("config-"+a,b[a],0,d))}l.baseUrl||(l.baseUrl="./");/\/$/.test(l.baseUrl)||(l.baseUrl+="/");for(a in b.has)n.add(a,b.has[a],0,d);p(b.packages,Da);for(var e in b.packagePaths)p(b.packagePaths[e],function(b){var d=e+"/"+b;u(b)&&(b={name:b});b.location=d;Da(b)});ja(m(za,b.map),P);p(P,function(b){b[1]=ja(b[1],[]);"*"==b[0]&&(P.star=b)});ja(m(Sa,b.paths),ya);Ta(b.aliases,xa);if(d)Ea.push({config:b.config});else for(a in b.config)d=
E(a,k),d.config=m(d.config||{},b.config[a]);b.cache&&(T(),Q=b.cache,b.cache["*noref"]&&T());G("config",[b,l.rawConfig])};n("dojo-cdn");var U=e.getElementsByTagName("script");var A=0;for(var B,K,V,M;A<U.length;)if(B=U[A++],(V=B.getAttribute("src"))&&(M=V.match(/(((.*)\/)|^)dojo\.js(\W|$)/i))&&(K=M[3]||"",c.baseUrl=c.baseUrl||K,J=B),V=B.getAttribute("data-dojo-config")||B.getAttribute("djConfig"))R=l.eval("({ "+V+" })","data-dojo-config"),J=B;l.rawConfig={};L(c,1);n("dojo-cdn")&&((H.dojo.location=K)&&
(K+="/"),H.dijit.location=K+"../dijit/",H.dojox.location=K+"../dojox/");L(a,1);L(R,1);var W=function(b){ka(function(){p(b.deps,Fa)})},wa=function(b,d,a,e,c){var k;if(u(b)){if((k=E(b,e,!0))&&k.executed)return k.result;throw q("undefinedModule",b);}D(b)||(L(b,0,e),b=d,d=a);if(D(b))if(b.length){a="require*"+F();for(var n,x=[],g=0;g<b.length;)n=b[g++],x.push(E(n,e));k=m(X("",a,0,""),{injected:2,deps:x,def:d||f,require:e?e.require:l,gc:1});w[k.mid]=k;W(k);var h=N&&!0;ka(function(){la(k,h)});k.executed||
C.push(k);Y()}else d&&d();return c},ia=function(b){if(!b)return l;var d=b.require;d||(d=function(a,e,c){return wa(a,e,c,b,d)},b.require=m(d,l),d.module=b,d.toUrl=function(d){return Aa(d,b)},d.toAbsMid=function(d){return ma(d,b)});return d},C=[],Z=[],y={},Va=function(b){b.injected=1;y[b.mid]=1;b.url&&(y[b.url]=b.pack||1);Ua()},aa=function(b){b.injected=2;delete y[b.mid];b.url&&delete y[b.url];g(y)&&Wa()},Xa=l.idle=function(){return!Z.length&&g(y)&&!C.length&&!N},na=function(b,d){if(d)for(var a=0;a<
d.length;a++)if(d[a][2].test(b))return d[a];return 0},Ga=function(b){var d=[];for(b=b.replace(/\\/g,"/").split("/");b.length;){var a=b.shift();if(".."==a&&d.length&&".."!=e){d.pop();var e=d[d.length-1]}else"."!=a&&d.push(e=a)}return d.join("/")},X=function(b,d,a,e){return{pid:b,mid:d,pack:a,url:e,executed:0,def:0}},Ha=function(b,d,a,e,c,n,f,g,h){var k,x,r;var Ba=/^\./.test(b);if(/(^\/)|(:)|(\.js$)/.test(b)||Ba&&!d)return X(0,b,0,b);b=Ga(Ba?d.mid+"/../"+b:b);if(/^\./.test(b))throw q("irrationalPath",
b);d&&(r=na(d.mid,n));(r=(r=r||n.star)&&na(b,r[1]))&&(b=r[1]+b.substring(r[3]));d=(M=b.match(/^([^\/]+)(\/(.+))?$/))?M[1]:"";(k=a[d])?b=d+"/"+(x=M[3]||k.main):d="";var m=0;p(g,function(d){var a=b.match(d[0]);a&&0<a.length&&(m=t(d[1])?b.replace(d[0],d[1]):d[1])});if(m)return Ha(m,0,a,e,c,n,f,g,h);if(a=e[b])return h?X(a.pid,a.mid,a.pack,a.url):e[b];e=(r=na(b,f))?r[1]+b.substring(r[3]):d?k.location+"/"+x:b;/(^\/)|(:)/.test(e)||(e=c+e);return X(d,b,k,Ga(e+".js"))},S=function(b,d,a){return Ha(b,d,H,w,
l.baseUrl,a?[]:P,a?[]:ya,a?[]:xa)},Ia=function(b,d,a){return b.normalize?b.normalize(d,function(b){return ma(b,a)}):ma(d,a)},Ja=0,E=function(b,d,a){var e;if(e=b.match(/^(.+?)!(.*)$/)){var k=E(e[1],d,a);5!==k.executed||k.load||oa(k);k.load?(e=Ia(k,e[2],d),b=k.mid+"!"+(k.dynamic?++Ja+"!":"")+e):(e=e[2],b=k.mid+"!"+ ++Ja+"!waitingForPlugin");b={plugin:k,mid:b,req:ia(d),prid:e}}else b=S(b,d);return w[b.mid]||!a&&(w[b.mid]=b)},ma=l.toAbsMid=function(b,d){return S(b,d).mid},Aa=l.toUrl=function(b,d){d=S(b+
"/x",d);var a=d.url;return Ka(0===d.pid?b:a.substring(0,a.length-5))},La={injected:2,executed:5,def:3,result:3},pa=function(b){return w[b]=m({mid:b},La)},Ya=pa("require"),Za=pa("exports"),$a=pa("module"),ba={},qa=0,oa=function(b){var d=b.result;b.dynamic=d.dynamic;b.normalize=d.normalize;b.load=d.load;return b},ab=function(b){var d={};p(b.loadQ,function(a){var e=Ia(b,a.prid,a.req.module),k=b.dynamic?a.mid.replace(/waitingForPlugin$/,e):b.mid+"!"+e;e=m(m({},a),{mid:k,prid:e,injected:0});w[k]||Ma(w[k]=
e);d[a.mid]=w[k];aa(a);delete w[a.mid]});b.loadQ=0;var a=function(b){for(var a=b.deps||[],e=0;e<a.length;e++)(b=d[a[e].mid])&&(a[e]=b)},e;for(e in w)a(w[e]);p(C,a)},ra=function(b){l.trace("loader-finish-exec",[b.mid]);b.executed=5;b.defOrder=qa++;b.loadQ&&(oa(b),ab(b));for(A=0;A<C.length;)C[A]===b?C.splice(A,1):A++;/^require\*/.test(b.mid)&&delete w[b.mid]},bb=[],la=function(b,a){if(4===b.executed)return l.trace("loader-circular-dependency",[bb.concat(b.mid).join("-\x3e")]),!b.def||a?ba:b.cjs&&b.cjs.exports;
if(!b.executed){if(!b.def)return ba;var d=b.mid,e=b.deps||[],c,n=[],f=0;for(b.executed=4;c=e[f++];){c=c===Ya?ia(b):c===Za?b.cjs.exports:c===$a?b.cjs:la(c,a);if(c===ba)return b.executed=0,l.trace("loader-exec-module",["abort",d]),ba;n.push(c)}l.trace("loader-run-factory",[b.mid]);a=b.def;n=t(a)?a.apply(null,n):a;b.result=void 0===n&&b.cjs?b.cjs.exports:n;ra(b)}return b.result},N=0,ka=function(b){try{N++,b()}finally{N--}Xa()&&G("idle",[])},Y=function(){N||ka(function(){for(var b,a,e=0;e<C.length;)b=
qa,a=C[e],la(a),b!=qa?e=0:e++})},Ka="function"==typeof a.fixupUrl?a.fixupUrl:function(b){b+="";return b+(ha?(/\?/.test(b)?"\x26":"?")+ha:"")},Ma=function(b){var a=b.plugin;5!==a.executed||a.load||oa(a);var e=function(a){b.result=a;aa(b);ra(b);Y()};a.load?a.load(b.prid,b.req,e):a.loadQ?a.loadQ.push(b):(a.loadQ=[b],C.unshift(a),Fa(a))},ca=0,sa=0,ta=0,cb=function(b,a){ta=1;b===ca?ca.call(null):l.eval(b,a.url);ta=0},Fa=function(b){var a=b.mid,e=b.url;if(!(b.executed||b.injected||y[a]||b.url&&(b.pack&&
y[b.url]===b.pack||1==y[b.url])))if(Va(b),b.plugin)Ma(b);else{var c=function(){db(b);if(2!==b.injected){if(n("dojo-enforceDefine")){G("error",q("noDefine",b));return}aa(b);m(b,La);l.trace("loader-define-nonmodule",[b.url])}Y()};(ca=I[a]||I["url:"+b.url])?(l.trace("loader-inject",["cache",b.mid,e]),cb(ca,b),c()):(l.trace("loader-inject",["script",b.mid,e]),sa=b,l.injectUrl(Ka(e),c,b),sa=0)}},ua=function(b,a,e){l.trace("loader-define-module",[b.mid,a]);if(2===b.injected)return G("error",q("multipleDefine",
b)),b;m(b,{deps:a,def:e,cjs:{id:b.mid,uri:b.url,exports:b.result={},setExports:function(a){b.cjs.exports=a},config:function(){return b.config}}});for(var d=0;a[d];d++)a[d]=E(a[d],b);aa(b);t(e)||a.length||(b.result=e,ra(b));return b},db=function(b,a){for(var d=[],e,c;Z.length;)c=Z.shift(),a&&(c[0]=a.shift()),e=c[0]&&E(c[0])||b,d.push([e,c[1],c[2]]);T(b);p(d,function(b){W(ua.apply(null,b))})},Wa=f,Ua=f;n.add("ie-event-behavior",e.attachEvent&&"undefined"===typeof Windows&&("undefined"===typeof opera||
"[object Opera]"!=opera.toString()));var va=function(b,a,e,c){if(n("ie-event-behavior"))return b.attachEvent(e,c),function(){b.detachEvent(e,c)};b.addEventListener(a,c,!1);return function(){b.removeEventListener(a,c,!1)}},eb=va(window,"load","onload",function(){l.pageLoaded=1;"complete"!=e.readyState&&(e.readyState="complete");eb()});U=e.getElementsByTagName("script");for(A=0;!J;)/^dojo/.test((B=U[A++])&&B.type)||(J=B);l.injectUrl=function(b,a,c){c=c.node=e.createElement("script");var d=va(c,"load",
"onreadystatechange",function(b){b=b||window.event;var e=b.target||b.srcElement;if("load"===b.type||/complete|loaded/.test(e.readyState))d(),f(),a&&a()}),f=va(c,"error","onerror",function(a){d();f();G("error",q("scriptError",[b,a]))});c.type="text/javascript";c.charset="utf-8";c.src=b;var r=n("qbo-error-logging-url-patterns");if(b&&r){var g=window.location.origin;g||(g=window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.protocol:""));0!==b.indexOf(g)&&
(new RegExp(r,"i")).test(b)&&c.setAttribute("crossorigin","anonymous")}J.parentNode.insertBefore(c,J);return c};l.log=f;l.trace=f;var Na=function(b,a,e){var d=arguments.length,c=["require","exports","module"],f=[0,b,a];1==d?f=[0,t(b)?c:[],b]:2==d&&u(b)?f=[b,t(a)?c:[],a]:3==d&&(f=[b,a,e]);l.trace("loader-define",f.slice(0,2));if((d=f[0]&&E(f[0]))&&!y[d.mid])W(ua(d,f[1],f[2]));else if(!n("ie-event-behavior")||ta)Z.push(f);else{d=d||sa;if(!d)for(b in y)if((c=w[b])&&c.node&&"interactive"===c.node.readyState){d=
c;break}d?(T(d),W(ua(d,f[1],f[2]))):G("error",q("ieDefineFailed",f[0]));Y()}};Na.amd={vendor:"dojotoolkit.org"};m(m(l,c.loaderPatch),a.loaderPatch);Ra("error",function(b){try{if(console.error(b),b instanceof Error){for(var a in b)console.log(a+":",b[a]);console.log(".")}}catch(k){}});m(l,{uid:F,cache:I,packs:H});if(!z.define){z.define=Na;z.require=l;p(Ea,function(b){L(b)});var Oa=R.deps||a.deps||c.deps,Pa=R.callback||a.callback||c.callback;l.boot=Oa||Pa?[Oa||[],Pa]:0}})(function(a){return a.dojoConfig||
a.djConfig||a.require||{}},{async:1,config:{"requirejs-text":{useXhr:function(a){return!!/^https?:\/\/[^/]+\.intuit\.com/.exec(a)||!!/^https?:\/\/[^/]+\.intuitcdn\.net/.exec(a)||!!/^\/c[0-9]+\/v[0-9.]+\/scripts\//.exec(a)||!(!qbo.classicStaticHost||!a||0!==a.indexOf(qbo.classicStaticHost))}}},hasCache:{"config-selectorEngine":"lite","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},map:{"*":{"@apollo/react-common":"APPFDEFAULT","@apollo/react-components":"APPFDEFAULT",
"@apollo/react-hoc":"APPFDEFAULT","@apollo/react-hooks":"APPFDEFAULT","@appfabric/intuit-analytics":"shell/lib/intuit-analytics/intuitAnalytics","@appfabric/tracking-core":"appfabric-tracking-core","@appfabric/ui-data-layer":"APPFDEFAULT","@appfabric/ui-intl":"appfabric-ui-intl","@appfabric/web-events-controller":"appfabric-web-events-controller","@babel/runtime":"@babel-runtime","@babel/runtime/regenerator":"@babel-runtime/regenerator/index","@sbg/harmony-react-components":"@sbg-harmony-react-components",
React:"react",ReactDOM:"react-dom","dojo/topic":"shell/util/CustomTopicImpl","ecosystem-app/shell/components/global-header/FlyoutView":"ecosystem-app-shell/components/global-header/public/FlyoutView","graphql-tag":"APPFDEFAULT",gsap:"APPFDEFAULT",hui:"APPFDEFAULT","hui-css":"APPFDEFAULT","hui-react":"APPFDEFAULT",moment:"APPFDEFAULT","moment/locales":"APPFDEFAULT","moment/moment-with-locales":"moment/momentLocale",morpheus:"web-shell-core","morpheus/View":"web-shell-core/views/View","payments-ui-services":"APPFDEFAULT",
pubsub:"@appfabric/pubsub",qbo:"qbo-ui/qbo","qbo-ui-gsap/gsap":"@appfabric/gsap","qbo-ui-libs-charts":"APPFDEFAULT","qbo-ui-services":"APPFDEFAULT","qbo-ui/qbo/lists/util":"neo/util/listUtil","qbo/404/404ViewController":"shell/404/404ViewController","qbo/base/WrapperModule":"shell/base/WrapperModule","qbo/base/app":"shell/base/app","qbo/base/appTrackHelper":"shell/base/appTrackHelper","qbo/base/shell":"shell/base/shell","qbo/boot":"shell/boot","qbo/dojoDeps":"shell/dojoDeps","qbo/lists/util":"neo/util/listUtil",
"qbo/login/loginHelper":"shell/login/loginHelper","qbo/login/templates/login":"shell/login/templates/login","qbo/mfa/MFAViewController":"shell/mfa/MFAViewController","qbo/reports/CommonMixin":"shell/reports/CommonMixin","qbo/reports/ReportListModel":"shell/reports/ReportListModel","qbo/reports/custom/CustomReportsListModel":"shell/reports/custom/CustomReportsListModel","qbo/shell/ShellViewMobileMixin":"shell/shell/ShellViewMobileMixin","qbo/shell/TESTCASE.md":"shell/shell/TESTCASE.md","qbo/shell/_newLayoutServiceMixin":"shell/shell/_newLayoutServiceMixin",
"qbo/shell/config":"shell/shell/config","qbo/shell/layoutService":"shell/shell/layoutService","qbo/shell/modulesLoadedAfterReady":"shell/shell/modulesLoadedAfterReady","qbo/shell/views/global-header/FlyoutView":"shell/shell/views/global-header/FlyoutView","qbo/shell/views/global-header/FlyoutViewFocusCycleMixin":"shell/shell/views/global-header/FlyoutViewFocusCycleMixin","qbo/shell/views/global-header/MenuFlyoutUtil":"shell/shell/views/global-header/MenuFlyoutUtil","qbo/shell/views/global-header/items/recents/RecentsFlyout":"shell/shell/views/global-header/items/recents/RecentsFlyout",
"qbo/shell/views/global-header/items/recents/templates/RecentsFlyoutView":"shell/shell/views/global-header/items/recents/templates/RecentsFlyoutView","qbo/util/selfServiceUtil":"shell/util/selfServiceUtil","qbo/util/xhrErrorHelper":"neo/util/xhrErrorHelper","qbo/widgets/closethebook/CloseTheBookDialogViewController":"neo/widgets/closethebook/CloseTheBookDialogViewController","qbo/widgets/quickfill/CentersSearchComboBox":"qbo/centers/widgets/CentersSearchComboBox","qbo/widgets/quickfill/CentersSearchComboBoxMixin":"qbo/centers/widgets/CentersSearchComboBoxMixin",
"qbo/widgets/quickfill/ComboBox":"neo/widgets/quickfill/ComboBox","qbo/widgets/quickfill/CustomQuickFillQueryEngine":"neo/widgets/quickfill/CustomQuickFillQueryEngine","qbo/widgets/quickfill/FilteringSelect":"neo/widgets/quickfill/FilteringSelect","qbo/widgets/quickfill/SearchComboBox":"neo/widgets/quickfill/SearchComboBox","qbo/widgets/quickfill/SearchComboBoxMixin":"neo/widgets/quickfill/SearchComboBoxMixin","qbo/widgets/quickfill/SearchFilteringSelect":"neo/widgets/quickfill/SearchFilteringSelect",
"qbo/widgets/quickfill/_SearchAutoCompleterMixin":"neo/widgets/quickfill/_SearchAutoCompleterMixin","qbo/widgets/quickfill/social/_ComboBoxMenu":"neo/widgets/quickfill/social/_ComboBoxMenu","qbo/widgets/quickfill/social/socialStores":"neo/widgets/quickfill/social/socialStores","qbo/widgets/quickfill/stores":"neo/widgets/quickfill/stores","react-relay":"APPFDEFAULT","react-relay/relay":"react-relay","react/react-dom-server":"react-dom/react-dom-server.browser.production.min","sbg-analytics-lib":"@sbg/analytics-lib",
text:"shell/util/requirejs-text-adapter/requirejs-text-adapter","ua-parser":"APPFDEFAULT","ua-parser-js":"APPFDEFAULT","ui-data-layer":"APPFDEFAULT","web-shell-core/BaseObject":"neo/util/BaseObject","web-shell-core/default/PluginRegistryService":"qbo-ui-libs-plugins/services/PluginRegistryService"},"@sbg/harmony-ui-components":{dgrid:"dgrid-0.4",hui:"@sbg/harmony-ui-components",text:"shell/util/requirejs-text-adapter/requirejs-text-adapter","ua-parser":"ua-parser-js"},hui:{dgrid:"dgrid-0.4",text:"shell/util/requirejs-text-adapter/requirejs-text-adapter",
"ua-parser":"ua-parser-js"}},packages:[{location:"../platform/@babel-runtime",name:"@babel-runtime"},{location:"../platform/appfabric-tracking-core",main:"tracking-core-lib-amd.min",name:"appfabric-tracking-core"},{location:"../platform/create-react-class",main:"create-react-class.min",name:"create-react-class"},{location:"../platform/dayjs",main:"dayjs.min",name:"dayjs"},{location:"../platform/dcl",main:"dcl.js",name:"dcl"},{location:"../platform/dgrid",main:"OnDemandGrid",name:"dgrid"},{location:"../platform/dgrid-0.4",
main:"OnDemandGrid",name:"dgrid-0.4"},{location:"../dijit",name:"dijit"},{location:".",name:"dojo"},{location:"../dojox",name:"dojox"},{location:"../dstore",main:"Store",name:"dstore"},{location:"../shell/ecosystem-app-shell",name:"ecosystem-app-shell"},{location:"../platform/gdpr-util",main:"gdprUtilClassBundle",name:"gdpr-util"},{location:"../platform/intuit-analytics",main:"intuit-analytics-bundle",name:"intuit-analytics"},{location:"../platform/intuit-authz",main:"intuit-authz",name:"intuit-authz"},
{location:"../platform/launchdarkly-js-client-sdk",main:"ldclient.min",name:"launchdarkly-js-client-sdk"},{location:"../platform/neo",name:"neo"},{location:"../platform/object-utils",name:"object-utils"},{location:"../platform/put-selector",main:"put",name:"put-selector"},{location:"../platform/qbo-ui-libs-math",name:"qbo-ui-libs-math"},{location:"../platform/qbo-ui-libs-plugins",name:"qbo-ui-libs-plugins"},{location:"../platform/qbo-ui-libs-xdm",name:"qbo-ui-libs-xdm"},{location:"../platform/requirejs-text",
main:"text",name:"requirejs-text"},{location:"../platform/appfabric-ui-intl",main:"index",name:"appfabric-ui-intl"},{location:"../shell",name:"shell"},{location:"../platform/underscore",main:"underscore",name:"underscore"},{location:"../platform/appfabric-web-events-controller",main:"index",name:"appfabric-web-events-controller"},{location:"../platform/xstyle",name:"xstyle"}]});
require({cache:{"xstyle/css":function(){define(["require"],function(a){function c(a,c,g){var f=document.documentElement;a=f.insertBefore(document.createElement(a),f.firstChild);a.id=c;c=(a.currentStyle||getComputedStyle(a,null)||{})[g];f.removeChild(a);return c}return{load:function(h,f,g,v){function t(a){var h=c("x-parse",null,"content"),m=a&&(a.sheet||a.styleSheet);h&&"none"!=h&&"normal"!=h?f([eval(h)],function(c){a?c.process(a,g):(c.processAll(),g(m))}):g(m)}var u=f.toUrl(h);if(u.match(/!$/)){var D=
{wait:!1};u=u.slice(0,-1)}var p=f.cache&&f.cache["url:"+u];if(null!=p)p.xCss&&(p=p.cssText),"string"==typeof p?a(["./core/load-css"],function(a){t(a.insertCss(p))}):t();else{if("none"==c("div",h.replace(/\//g,"-").replace(/\..*/,"")+"-loaded","display"))return t();a(["./core/load-css"],function(a){a(u,t,D)})}}}})},"xstyle/core/load-css":function(){define([],function(){function a(a){if(f.createStyleSheet){var c=f.createStyleSheet();c.cssText=a;return c.owningElement}c=f.createElement("style");c.setAttribute("type",
"text/css");c.appendChild(f.createTextNode(a));g.appendChild(c);return c}function c(c,t,u){var v=h[c];if(v)return p=a(v),t(p);var p=f.createElement("link");p.type="text/css";p.rel="stylesheet";p.href=c;var m=!u||!1!==u.wait;u=(u=navigator.userAgent.match(/AppleWebKit\/(\d+\.?\d*)/))&&+u[1];if(null===p.onload&&!(536>u))p.onload=function(){p.onload=null;p.onerror=null;m&&t(p)},p.onerror=function(){console.error("Error loading stylesheet "+c);m&&t(p)};else if(m)var q=setInterval(function(){p.style&&
(clearInterval(q),t(p))},15);(g||f.getElementsByTagName("head")[0]).appendChild(p);m||t(p)}var h="undefined"==typeof _css_cache?{}:_css_cache,f=document,g=f.head;c.insertCss=a;return c})},"shell/util/requirejs-text-adapter/requirejs-text-adapter":function(){define(["requirejs-text"],function(a){return{normalize:function(a,h){return h(a)},load:function(c,h,f,g){var v=c.split("!");v=require.toUrl(v[0]);require.cache&&"url:"+v in require.cache?require(["dojo/text"],function(a){a.load(c,h,f,g)}):a.load(c,
h,f,g)}}})},"requirejs-text/text":function(){define(["module"],function(a){function c(a,c){return void 0===a||""===a?c:a}var h=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],f=/^\s*<\?xml(\s)+version=['"](\d)*.(\d)*['"](\s)*\?>/im,g=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im,v="undefined"!==typeof location&&location.href,t=v&&location.protocol&&location.protocol.replace(/:/,""),u=v&&location.hostname,D=v&&(location.port||void 0),p={},m=a.config&&a.config()||{};var q={version:"2.0.16",strip:function(a){if(a){a=
a.replace(f,"");var c=a.match(g);c&&(a=c[1])}else a="";return a},jsEscape:function(a){return a.replace(/(['\\])/g,"\\$1").replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r").replace(/[\u2028]/g,"\\u2028").replace(/[\u2029]/g,"\\u2029")},createXhr:m.createXhr||function(){var a;if("undefined"!==typeof XMLHttpRequest)return new XMLHttpRequest;if("undefined"!==typeof ActiveXObject)for(a=0;3>a;a+=1){var c=h[a];try{var f=new ActiveXObject(c)}catch(r){}if(f){h=
[c];break}}return f},parseName:function(a){var c=!1,e=a.lastIndexOf(".");var f=0===a.indexOf("./")||0===a.indexOf("../");if(-1!==e&&(!f||1<e)){f=a.substring(0,e);var g=a.substring(e+1)}else f=a;a=g||f;e=a.indexOf("!");-1!==e&&(c="strip"===a.substring(e+1),a=a.substring(0,e),g?g=a:f=a);return{moduleName:f,ext:g,strip:c}},xdRegExp:/^((\w+):)?\/\/([^\/\\]+)/,useXhr:function(a,f,g,r){var e=q.xdRegExp.exec(a);if(!e)return!0;a=e[2];var n=e[3];n=n.split(":");e=n[1];n=n[0];if((g=(!a||a===f)&&(!n||n.toLowerCase()===
g.toLowerCase()))&&!(g=!e&&!n))a:if(e===r)g=!0;else{if(a===f)if("http"===a){g=c(e,"80")===c(r,"80");break a}else if("https"===a){g=c(e,"443")===c(r,"443");break a}g=!1}return g},finishLoad:function(a,c,f,g){f=c?q.strip(f):f;m.isBuild&&(p[a]=f);g(f)},load:function(a,c,f,g){if(g&&g.isBuild&&!g.inlineText)f();else{m.isBuild=g&&g.isBuild;var e=q.parseName(a);g=e.moduleName+(e.ext?"."+e.ext:"");var h=c.toUrl(g),n=m.useXhr||q.useXhr;0===h.indexOf("empty:")?f():!v||n(h,t,u,D)?q.get(h,function(c){q.finishLoad(a,
e.strip,c,f)},function(a){f.error&&f.error(a)}):c([g],function(a){q.finishLoad(e.moduleName+"."+e.ext,e.strip,a,f)},function(a){f.error&&f.error(a)})}},write:function(a,c,f,g){p.hasOwnProperty(c)&&(g=q.jsEscape(p[c]),f.asModule(a+"!"+c,"define(function () { return '"+g+"';});\n"))},writeFile:function(a,c,f,g,h){c=q.parseName(c);var e=c.ext?"."+c.ext:"",n=c.moduleName+e,l=f.toUrl(c.moduleName+e)+".js";q.load(n,f,function(c){c=function(a){return g(l,a)};c.asModule=function(a,c){return g.asModule(a,
l,c)};q.write(a,n,c,h)},h)}};if("node"===m.env||!m.env&&"undefined"!==typeof process&&process.versions&&process.versions.node&&!process.versions["node-webkit"]&&!process.versions["atom-shell"]){var da=require.nodeRequire("fs");q.get=function(a,c,f){try{var e=da.readFileSync(a,"utf8");"\ufeff"===e[0]&&(e=e.substring(1));c(e)}catch(O){f&&f(O)}}}else if("xhr"===m.env||!m.env&&q.createXhr())q.get=function(a,c,f,g){var e=q.createXhr(),h;e.open("GET",a,!0);if(g)for(h in g)g.hasOwnProperty(h)&&e.setRequestHeader(h.toLowerCase(),
g[h]);if(m.onXhr)m.onXhr(e,a);e.onreadystatechange=function(g){if(4===e.readyState&&(g=e.status||0,399<g&&600>g?(g=Error(a+" HTTP status: "+g),g.xhr=e,f&&f(g)):c(e.responseText),m.onXhrComplete))m.onXhrComplete(e,a)};e.send(null)};else if("rhino"===m.env||!m.env&&"undefined"!==typeof Packages&&"undefined"!==typeof java)q.get=function(a,c){var e,f=new java.io.File(a);a=java.lang.System.getProperty("line.separator");f=new java.io.BufferedReader(new java.io.InputStreamReader(new java.io.FileInputStream(f),
"utf-8"));var g="";try{var h=new java.lang.StringBuffer;(e=f.readLine())&&e.length()&&65279===e.charAt(0)&&(e=e.substring(1));for(null!==e&&h.append(e);null!==(e=f.readLine());)h.append(a),h.append(e);g=String(h.toString())}finally{f.close()}c(g)};else if("xpconnect"===m.env||!m.env&&"undefined"!==typeof Components&&Components.classes&&Components.interfaces){var F=Components.classes;var l=Components.interfaces;Components.utils["import"]("resource://gre/modules/FileUtils.jsm");var z="@mozilla.org/windows-registry-key;1"in
F;q.get=function(a,c){var f={};z&&(a=a.replace(/\//g,"\\"));a=new FileUtils.File(a);try{var e=F["@mozilla.org/network/file-input-stream;1"].createInstance(l.nsIFileInputStream);e.init(a,1,0,!1);var g=F["@mozilla.org/intl/converter-input-stream;1"].createInstance(l.nsIConverterInputStream);g.init(e,"utf-8",e.available(),l.nsIConverterInputStream.DEFAULT_REPLACEMENT_CHARACTER);g.readString(e.available(),f);g.close();e.close();c(f.value)}catch(ea){throw Error((a&&a.path||"")+": "+ea);}}}return q})},
"shell/base/loader":function(){define(["@babel/runtime/helpers/interopRequireDefault","shell/util/requirejs-text-adapter/requirejs-text-adapter"],function(){return{load:function(a,c){var h=function(a){c(a)};if(!a)throw Error("loader config is not defined");a.layers=Object.assign({app:[],boot:[],css:[],afterPageReady:[]},a.layers);a.layers.css=a.layers.css.map(function(a){return"xstyle/css!"+a});a.useLayers?(a.layers.boot.push.apply(a.layers.boot,a.layers.css),0<a.layers.boot.length?(window.performance&&
window.performance.mark&&window.performance.mark("BOOT_LAYERS_LOAD_START"),window.require(a.layers.boot,function(){window.performance&&window.performance.measure&&window.performance.measure("BOOT_LAYERS_LOAD","BOOT_LAYERS_LOAD_START");c(null,a.layers)},h)):c(null,a.layers)):0<a.layers.css.length?window.require(a.layers.css,function(){c(null,a.layers)},c):c(null,a.layers)}}})},"@babel-runtime/helpers/interopRequireDefault":function(){define("@babel-runtime/helpers/interopRequireDefault",[],function(){return function(a){function c(f){if(h[f])return h[f].exports;
var g=h[f]={i:f,l:!1,exports:{}};return a[f].call(g.exports,g,g.exports,c),g.l=!0,g.exports}var h={};return c.m=a,c.c=h,c.d=function(a,g,h){c.o(a,g)||Object.defineProperty(a,g,{configurable:!1,enumerable:!0,get:h})},c.r=function(a){Object.defineProperty(a,"__esModule",{value:!0})},c.n=function(a){var f=a&&a.__esModule?function(){return a.default}:function(){return a};return c.d(f,"a",f),f},c.o=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)},c.p="",c(c.s=60)}({60:function(a,c){a.exports=
function(a){return a&&a.__esModule?a:{default:a}};a.exports.__esModule=!0;a.exports.default=a.exports}})})},"shell/applications/default/config":function(){define([],function(){return{getLayers:function(a){window.qbo=window.qbo||window.appContext;a=a||{};return{boot:this._getBootLayers(),app:this._getAppLayers(),afterPageReady:this._getAfterPageReadyLayers(),css:this._getCSSLayers(a)}},getAppHandler:function(a,c){var h=this;return function(a,g){if(a)throw a;h._loadWebShellAdapter(g,c)}},_loadWebShellAdapter:function(a,
c){window.performance&&window.performance.mark&&window.performance.mark("WEB_SHELL_ADAPTER_LOAD_START");window.require(["shell/base/webShellAdapter"],function(h){window.performance&&window.performance.measure&&window.performance.measure("WEB_SHELL_ADAPTER_LOAD","WEB_SHELL_ADAPTER_LOAD_START");h=h.getAppConfig();h.appLayers.splice(0,h.appLayers.length);h.appLayers.push.apply(h.appLayers,a.app);h.afterPageReadyLayers.splice(0,h.afterPageReadyLayers.length);h.afterPageReadyLayers.push.apply(h.afterPageReadyLayers,
a.afterPageReady);c&&c()})},_getBootLayers:function(){return["shell/boot"]},_getCurrentUrl:function(){return window.location.pathname},_shouldDelayLegacyAppLayersByRoute:function(){return-1!==this._getCurrentUrl().search(new RegExp(`^\/${window.__shellInternal.appExperience.navigationRoot}\/(homepage|clients|get-things-done|business-overview)$`))},_shouldDisableLegacyAppLayersPreloading:function(){var a=qbo&&qbo.pluginsInfo&&qbo.pluginsInfo.plugins&&qbo.pluginsInfo.plugins["sbg-web-shell-ui"];return a&&
a.extendedProperties?!0===a.extendedProperties.disableLegacyAppLayersPreloading:!1},_getAppLayers:function(){var a=["shell/dojoDeps","shell/legacyDeps","shell/appReadyDeps"];this._shouldDisableLegacyAppLayersPreloading()&&a.splice(0,2);this._shouldDelayLegacyAppLayersByRoute()?a=["shell/appReadyDeps"]:a.push("hui/hui");return a},_getAfterPageReadyLayers:function(){var a=["shell/dojoDeps","shell/legacyDeps","shell/afterPageReadyDeps"];this._shouldDisableLegacyAppLayersPreloading()&&a.splice(0,2);return a=
this._shouldDelayLegacyAppLayersByRoute()?a.concat(["hui/hui"]):["shell/afterPageReadyDeps"]},_getCSSLayers:function(a){var c=["hui/css/hui.min.css"];c=c.concat(["shell/harmony/ecosystem-app/main.css","shell/harmony/harmony-common.css"]);a=a||{};a.isVO&&c.push("shell/harmony/VO.css");a.flags&&c.push("shell/harmony/flags.css");a.embedded&&c.push("shell/harmony/QBOMac.css");return c}}})},"shell/applications/embedded-mobile/config":function(){define([],function(){return{getLayers:function(){return{boot:["shell/embeddedMobileBoot"],
app:["shell/embeddedMobileDojoDeps","shell/embeddedMobileWidgets","hui/hui"],css:["ui-components-web-react/css","hui/css/hui.min.css","shell/harmony/ecosystem-app/main.css","shell/harmony/harmony-common.css"],afterPageReady:[]}},getAppHandler:function(a,c){return function(a,f){if(a)throw a;window.require(["shell/applications/embedded-mobile/webShellAdapter"],function(a){a=a.getAppConfig();a.appLayers.splice(0,a.appLayers.length);a.appLayers.push.apply(a.appLayers,f.app);c&&c()})}}}})},"@babel-runtime/helpers/typeof":function(){define("@babel-runtime/helpers/typeof",
[],function(){return function(a){function c(f){if(h[f])return h[f].exports;var g=h[f]={i:f,l:!1,exports:{}};return a[f].call(g.exports,g,g.exports,c),g.l=!0,g.exports}var h={};return c.m=a,c.c=h,c.d=function(a,g,h){c.o(a,g)||Object.defineProperty(a,g,{configurable:!1,enumerable:!0,get:h})},c.r=function(a){Object.defineProperty(a,"__esModule",{value:!0})},c.n=function(a){var f=a&&a.__esModule?function(){return a.default}:function(){return a};return c.d(f,"a",f),f},c.o=function(a,c){return Object.prototype.hasOwnProperty.call(a,
c)},c.p="",c(c.s=0)}([function(a,c){function h(c){"@babel/helpers - typeof";return a.exports=h="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},a.exports.__esModule=!0,a.exports.default=a.exports,h(c)}a.exports=h;a.exports.__esModule=!0;a.exports.default=a.exports}])})}}});require.boot&&require.apply(null,require.boot);
//# sourceMappingURL=dojo.js.map